def get_categories():
    return [

        {"id":1,"name":"AI Models","slug":"ai-models"},
        {"id":2,"name":"LLM APIs","slug":"llm-apis"},
        {"id":3,"name":"Vector Databases","slug":"vector-databases"},
        {"id":4,"name":"Databases","slug":"databases"},
        {"id":5,"name":"Backend","slug":"backend"},
        {"id":6,"name":"Frontend","slug":"frontend"},
        {"id":7,"name":"Hosting","slug":"hosting"},
        {"id":8,"name":"Authentication","slug":"authentication"},
        {"id":9,"name":"Payments","slug":"payments"},
        {"id":10,"name":"Storage","slug":"storage"},
        {"id":11,"name":"Email","slug":"email"},
        {"id":12,"name":"Analytics","slug":"analytics"},
        {"id":13,"name":"Monitoring","slug":"monitoring"},
        {"id":14,"name":"Logging","slug":"logging"},
        {"id":15,"name":"Search","slug":"search"},
        {"id":16,"name":"CMS","slug":"cms"},
        {"id":17,"name":"Automation","slug":"automation"},
        {"id":18,"name":"Cloud","slug":"cloud"},
        {"id":19,"name":"Containers","slug":"containers"},
        {"id":20,"name":"CI/CD","slug":"ci-cd"},
        {"id":21,"name":"Mobile","slug":"mobile"},
        {"id":22,"name":"DevOps","slug":"devops"},
        {"id":23,"name":"Security","slug":"security"},
        {"id":24,"name":"Testing","slug":"testing"},
        {"id":25,"name":"UI Libraries","slug":"ui-libraries"},
        {"id":26,"name":"CSS","slug":"css"},
        {"id":27,"name":"Icons","slug":"icons"},
        {"id":28,"name":"Charts","slug":"charts"},
        {"id":29,"name":"Maps","slug":"maps"},
        {"id":30,"name":"Video","slug":"video"},
        {"id":31,"name":"Audio","slug":"audio"},
        {"id":32,"name":"OCR","slug":"ocr"},
        {"id":33,"name":"Translation","slug":"translation"},
        {"id":34,"name":"Image Generation","slug":"image-generation"},
        {"id":35,"name":"Speech","slug":"speech"},
        {"id":36,"name":"Robotics","slug":"robotics"},
        {"id":37,"name":"Game Engines","slug":"game-engines"},
        {"id":38,"name":"IoT","slug":"iot"},
        {"id":39,"name":"Blockchain","slug":"blockchain"},
        {"id":40,"name":"Web3","slug":"web3"},
        {"id":41,"name":"CRM","slug":"crm"},
        {"id":42,"name":"ERP","slug":"erp"},
        {"id":43,"name":"Marketing","slug":"marketing"},
        {"id":44,"name":"SEO","slug":"seo"},
        {"id":45,"name":"Ads","slug":"ads"},
        {"id":46,"name":"Forms","slug":"forms"},
        {"id":47,"name":"Scheduling","slug":"scheduling"},
        {"id":48,"name":"Notifications","slug":"notifications"},
        {"id":49,"name":"Productivity","slug":"productivity"},
        {"id":50,"name":"Customer Support","slug":"customer-support"},
        {"id":51,"name":"AI Agents","slug":"ai-agents"},
        {"id":52,"name":"Code Editors","slug":"code-editors"},
        {"id":53,"name":"Package Managers","slug":"package-managers"},
        {"id":54,"name":"API Testing","slug":"api-testing"},
        {"id":55,"name":"Documentation","slug":"documentation"},
        {"id":56,"name":"Machine Learning","slug":"machine-learning"},
        {"id":57,"name":"MLOps","slug":"mlops"},
        {"id":58,"name":"Data Engineering","slug":"data-engineering"},
        {"id":59,"name":"Web Scraping","slug":"web-scraping"},
        {"id":60,"name":"Developer Tools","slug":"developer-tools"}

    ]