import type { CategoryRecord } from '../schema';

const now = '2026-01-01T00:00:00.000Z';

export const categoriesSeed: CategoryRecord[] = [
  {
    id: 'frontend',
    name: 'Frontend',
    slug: 'frontend',
    icon: 'layout',
    description: 'Frameworks and libraries for building fast, accessible user interfaces.',
    aliases: ['ui', 'web-frontend', 'frontend-framework', 'spa'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'backend',
    name: 'Backend',
    slug: 'backend',
    icon: 'server',
    description: 'Server-side frameworks and runtimes for APIs, services, and business logic.',
    aliases: ['api', 'server', 'web-backend', 'backend-framework'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'authentication',
    name: 'Authentication',
    slug: 'authentication',
    icon: 'shield-check',
    description: 'OAuth, magic links, biometrics, and session management for secure user login.',
    aliases: ['auth', 'authn', 'user-auth', 'sign-in', 'login'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'database',
    name: 'Database',
    slug: 'database',
    icon: 'database',
    description: 'SQL, NoSQL, vector, and real-time databases to store and query your data.',
    aliases: ['databases', 'db', 'datastore', 'data-store'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'hosting',
    name: 'Hosting',
    slug: 'hosting',
    icon: 'cloud',
    description: 'Deploy and scale your frontend, backend, and serverless functions globally.',
    aliases: ['host', 'web-hosting', 'app-hosting'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cloud',
    name: 'Cloud',
    slug: 'cloud',
    icon: 'cloud-cog',
    description: 'Compute, IaaS, and managed infrastructure from major cloud providers.',
    aliases: ['cloud-provider', 'iaas', 'cloud-infrastructure'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'storage',
    name: 'Storage',
    slug: 'storage',
    icon: 'hard-drive',
    description: 'File and object storage solutions for images, videos, and user uploads.',
    aliases: ['file-storage', 'object-storage', 'blob-storage'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'payments',
    name: 'Payments',
    slug: 'payments',
    icon: 'credit-card',
    description: 'Payment processing, subscriptions, and billing infrastructure.',
    aliases: ['payment', 'billing', 'payments-processing', 'merchant'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'email',
    name: 'Email',
    slug: 'email',
    icon: 'mail',
    description: 'Transactional and marketing email APIs with templates and deliverability.',
    aliases: ['emails', 'email-sending', 'transactional-email', 'email-api'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'analytics',
    name: 'Analytics',
    slug: 'analytics',
    icon: 'bar-chart-3',
    description: 'Product analytics, event tracking, and user behavior insights.',
    aliases: ['product-analytics', 'web-analytics', 'analytics-tracking'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ai-models',
    name: 'AI Models',
    slug: 'ai-models',
    icon: 'brain-circuit',
    description: 'Model infrastructure and platforms for hosting, running, and serving AI models.',
    aliases: ['model-inference', 'model-hosting', 'ai-infrastructure', 'ml-platform'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'llm',
    name: 'LLM',
    slug: 'llm',
    icon: 'sparkles',
    description: 'Large language model APIs for generation, reasoning, and AI assistants.',
    aliases: ['large-language-models', 'llms', 'genai', 'language-models'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'search',
    name: 'Search',
    slug: 'search',
    icon: 'search',
    description: 'Full-text, typo-tolerant, and vector search engines for instant results.',
    aliases: ['full-text-search', 'vector-search', 'search-engine', 'search-api'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'caching',
    name: 'Caching',
    slug: 'caching',
    icon: 'zap',
    description: 'In-memory data stores and caching layers for speed and scale.',
    aliases: ['cache', 'redis-cache', 'in-memory-store', 'cache-layer'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'monitoring',
    name: 'Monitoring',
    slug: 'monitoring',
    icon: 'activity',
    description: 'Metrics, dashboards, and alerting to keep your application healthy.',
    aliases: ['observability', 'app-monitoring', 'metrics', 'uptime'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'logging',
    name: 'Logging',
    slug: 'logging',
    icon: 'scroll-text',
    description: 'Centralized log management, search, and analysis.',
    aliases: ['log-management', 'logs', 'log-aggregation', 'log-analysis'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cms',
    name: 'CMS',
    slug: 'cms',
    icon: 'file-text',
    description: 'Content management systems for structured and unstructured content.',
    aliases: ['content-management', 'headless-cms', 'content'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'deployment',
    name: 'Deployment',
    slug: 'deployment',
    icon: 'rocket',
    description: 'App platforms and pipelines for shipping code to production.',
    aliases: ['deploys', 'releases', 'app-platform', 'deploy'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'maps',
    name: 'Maps',
    slug: 'maps',
    icon: 'map',
    description: 'Mapping, geocoding, and location services for apps and dashboards.',
    aliases: ['mapping', 'geolocation', 'map-services', 'geo'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ocr',
    name: 'OCR',
    slug: 'ocr',
    icon: 'scan-text',
    description: 'Optical character recognition to extract text from images and documents.',
    aliases: ['optical-character-recognition', 'document-ai', 'text-extraction'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'translation',
    name: 'Translation',
    slug: 'translation',
    icon: 'languages',
    description: 'Machine translation and localization APIs.',
    aliases: ['i18n', 'localization', 'language-translation', 'translator'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'voice',
    name: 'Voice',
    slug: 'voice',
    icon: 'mic',
    description: 'Speech-to-text, text-to-speech, and voice telephony APIs.',
    aliases: ['speech', 'tts', 'stt', 'speech-recognition'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'chat',
    name: 'Chat',
    slug: 'chat',
    icon: 'message-circle',
    description: 'Realtime chat and messaging APIs for in-app conversations.',
    aliases: ['messaging', 'realtime-chat', 'chat-api', 'conversations'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'notifications',
    name: 'Notifications',
    slug: 'notifications',
    icon: 'bell',
    description: 'Push notifications, in-app messaging, and multi-channel alert systems.',
    aliases: ['push-notifications', 'notification', 'push', 'alerts'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'testing',
    name: 'Testing',
    slug: 'testing',
    icon: 'flask-conical',
    description: 'Unit, integration, and end-to-end testing frameworks and runners.',
    aliases: ['unit-testing', 'e2e-testing', 'test', 'qa'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'devops',
    name: 'DevOps',
    slug: 'devops',
    icon: 'settings',
    description: 'Infrastructure as code and operations tooling for reliable delivery.',
    aliases: ['infrastructure-as-code', 'iac', 'ops', 'provisioning'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'containerization',
    name: 'Containerization',
    slug: 'containerization',
    icon: 'container',
    description: 'Containers and orchestration platforms to package and run services.',
    aliases: ['containers', 'orchestration', 'kubernetes', 'docker'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'serverless',
    name: 'Serverless',
    slug: 'serverless',
    icon: 'zap',
    description: 'Functions and edge compute platforms that scale to zero.',
    aliases: ['functions', 'faas', 'edge-functions', 'edge-compute'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ci-cd',
    name: 'CI/CD',
    slug: 'ci-cd',
    icon: 'git-branch',
    description: 'Continuous integration and delivery pipelines for automated builds.',
    aliases: ['cicd', 'pipelines', 'continuous-integration', 'continuous-deployment'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'video-apis',
    name: 'Video APIs',
    slug: 'video-apis',
    icon: 'video',
    description: 'Video streaming, transcoding, live streaming, and player SDKs.',
    aliases: ['video', 'video-streaming', 'video-hosting'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cdn',
    name: 'CDN',
    slug: 'cdn',
    icon: 'globe',
    description: 'Global content delivery networks for low-latency asset distribution.',
    aliases: ['content-delivery', 'edge-cdn', 'edge-network'],
    createdAt: now,
    updatedAt: now,
  },
];
