import { buildProviders, type SeedProvider } from './helpers';

const rows: SeedProvider[] = [
  {
    categoryId: 'cms',
    name: 'Sanity',
    shortDescription: 'Structured content platform with real-time collaboration.',
    longDescription:
      'Sanity is a headless CMS with a real-time, customizable editing studio and a flexible content API.',
    website: 'https://www.sanity.io',
    docs: 'https://www.sanity.io/docs',
    github: 'sanity-io/sanity',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 88,
    featured: true,
    features: ['Structured content', 'Real-time studio', 'Customizable', 'Content API'],
    tags: ['Headless CMS', 'Structured content', 'Realtime'],
    alternatives: ['contentful', 'strapi'],
  },
  {
    categoryId: 'cms',
    name: 'Contentful',
    shortDescription: 'Enterprise headless CMS with a powerful content API.',
    longDescription:
      'Contentful is a leading headless CMS used by enterprises for omnichannel content delivery.',
    website: 'https://www.contentful.com',
    docs: 'https://www.contentful.com/developers/docs',
    github: 'contentful/contentful.js',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 86,
    features: ['Content API', 'Editorial workflows', 'Localization', 'SDKs'],
    tags: ['Headless CMS', 'Enterprise', 'API'],
    alternatives: ['sanity', 'strapi'],
  },
  {
    categoryId: 'cms',
    name: 'Strapi',
    shortDescription: 'Open-source headless CMS you fully control.',
    longDescription:
      'Strapi is a self-hostable, open-source headless CMS with an admin panel and REST/GraphQL APIs.',
    website: 'https://strapi.io',
    docs: 'https://docs.strapi.io',
    github: 'strapi/strapi',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 85,
    features: ['Open source', 'Admin panel', 'REST and GraphQL', 'Self-hosted'],
    tags: ['Headless CMS', 'Open source', 'Self-hosted'],
    alternatives: ['directus', 'sanity'],
  },
  {
    categoryId: 'cms',
    name: 'Directus',
    shortDescription: 'Open-source data platform wrapping any SQL database.',
    longDescription:
      'Directus turns any SQL database into a REST and GraphQL API with an instant admin app.',
    website: 'https://directus.io',
    docs: 'https://docs.directus.io',
    github: 'directus/directus',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 82,
    features: ['SQL database wrapper', 'Instant admin app', 'REST and GraphQL', 'Open source'],
    tags: ['Headless CMS', 'Open source', 'SQL'],
    alternatives: ['strapi', 'payload'],
  },
  {
    categoryId: 'cms',
    name: 'Payload',
    shortDescription: 'TypeScript headless CMS built for developers.',
    longDescription:
      'Payload is a fully open-source, TypeScript-first headless CMS that lives in your codebase.',
    website: 'https://payloadcms.com',
    docs: 'https://payloadcms.com/docs',
    github: 'payloadcms/payload',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 80,
    features: ['TypeScript first', 'Code-based config', 'REST and GraphQL', 'Self-hosted'],
    tags: ['Headless CMS', 'TypeScript', 'Open source'],
    alternatives: ['strapi', 'directus'],
  },
  {
    categoryId: 'cms',
    name: 'KeystoneJS',
    shortDescription: 'GraphQL-based CMS and application framework.',
    longDescription:
      'KeystoneJS is a GraphQL-based CMS and Node.js application framework with flexible content modeling.',
    website: 'https://keystonejs.com',
    docs: 'https://keystonejs.com/docs',
    github: 'keystonejs/keystone',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 74,
    features: ['GraphQL API', 'Flexible models', 'Admin UI', 'Open source'],
    tags: ['Headless CMS', 'GraphQL', 'Open source'],
    alternatives: ['payload', 'strapi'],
  },
  {
    categoryId: 'cms',
    name: 'WordPress',
    shortDescription: 'The most widely used CMS powering 40% of the web.',
    longDescription:
      'WordPress is the world\u2019s most popular CMS, offering a mature plugin ecosystem for blogs and content sites.',
    website: 'https://wordpress.org',
    docs: 'https://developer.wordpress.org',
    github: 'WordPress/wordpress-develop',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 95,
    features: ['Plugin ecosystem', 'Themes', 'REST API', 'Block editor'],
    tags: ['CMS', 'Open source', 'Blog'],
    alternatives: ['sanity', 'contentful'],
  },
  {
    categoryId: 'deployment',
    name: 'Vercel',
    shortDescription: 'Instant Git-based deployments with global edge network.',
    longDescription:
      'Vercel deploys from Git with preview environments, instant rollbacks, and a global edge network.',
    website: 'https://vercel.com',
    docs: 'https://vercel.com/docs',
    github: 'vercel/vercel',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 95,
    featured: true,
    features: ['Git deploys', 'Preview environments', 'Edge network', 'Rollbacks'],
    tags: ['Deploy', 'Preview', 'Edge'],
    alternatives: ['netlify', 'cloudflare-pages'],
  },
  {
    categoryId: 'deployment',
    name: 'Netlify',
    shortDescription: 'Continuous deployment with atomic deploys and rollbacks.',
    longDescription:
      'Netlify provides continuous deployment from Git with atomic deploys, rollbacks, and a global CDN.',
    website: 'https://www.netlify.com',
    docs: 'https://docs.netlify.com',
    github: 'netlify/netlify',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 88,
    features: ['Git deploys', 'Atomic deploys', 'Rollbacks', 'Global CDN'],
    tags: ['Deploy', 'Git-based', 'Static'],
    alternatives: ['vercel', 'cloudflare-pages'],
  },
  {
    categoryId: 'deployment',
    name: 'Cloudflare Pages',
    shortDescription: 'Global static and functions deployment with previews.',
    longDescription:
      'Cloudflare Pages offers fast, global deployment for static sites and functions with preview deployments.',
    website: 'https://pages.cloudflare.com',
    docs: 'https://developers.cloudflare.com/pages',
    github: 'cloudflare/workers-sdk',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 85,
    features: ['Global deploys', 'Functions', 'Preview deploys', 'Unlimited bandwidth'],
    tags: ['Deploy', 'Edge', 'Static'],
    alternatives: ['vercel', 'netlify'],
  },
  {
    categoryId: 'deployment',
    name: 'Railway',
    shortDescription: 'Deploy any app from GitHub in seconds.',
    longDescription:
      'Railway deploys apps and databases from GitHub or templates with automatic restarts and scaling.',
    website: 'https://railway.app',
    docs: 'https://docs.railway.app',
    github: 'railwayapp/railway',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 83,
    features: ['Git deploys', 'Templates', 'Databases', 'Autoscaling'],
    tags: ['Deploy', 'Full-stack', 'Zero config'],
    alternatives: ['render', 'koyeb'],
  },
  {
    categoryId: 'deployment',
    name: 'Render',
    shortDescription: 'Deploy web services, workers, and databases from Git.',
    longDescription:
      'Render deploys web services, background workers, and databases from Git with blue-green deploys.',
    website: 'https://render.com',
    docs: 'https://render.com/docs',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 82,
    features: ['Git deploys', 'Blue-green deploys', 'Workers', 'Managed databases'],
    tags: ['Deploy', 'Full-stack', 'Managed'],
    alternatives: ['railway', 'koyeb'],
  },
  {
    categoryId: 'deployment',
    name: 'Koyeb',
    shortDescription: 'Global serverless platform with Git-driven deploys.',
    longDescription:
      'Koyeb is a global serverless platform that deploys from Git to edge and dedicated regions.',
    website: 'https://www.koyeb.com',
    docs: 'https://www.koyeb.com/docs',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 74,
    features: ['Git deploys', 'Global regions', 'Serverless', 'Functions'],
    tags: ['Deploy', 'Serverless', 'Global'],
    alternatives: ['railway', 'render'],
  },
  {
    categoryId: 'deployment',
    name: 'SST',
    shortDescription: 'Build and deploy full-stack apps on AWS.',
    longDescription:
      'SST is a framework for building and deploying full-stack apps on AWS with a great developer experience.',
    website: 'https://sst.dev',
    docs: 'https://sst.dev/docs',
    github: 'sst/sst',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 78,
    features: ['AWS deploys', 'Live Lambda', 'Serverless framework', 'Open source'],
    tags: ['Deploy', 'AWS', 'Serverless'],
    alternatives: ['amplify', 'vercel'],
  },
  {
    categoryId: 'maps',
    name: 'Google Maps Platform',
    shortDescription: 'Comprehensive maps, routing, and places APIs.',
    longDescription:
      'Google Maps Platform provides maps, geocoding, routing, and places APIs used by millions of apps.',
    website: 'https://mapsplatform.google.com',
    docs: 'https://developers.google.com/maps',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 96,
    featured: true,
    features: ['Interactive maps', 'Geocoding', 'Directions', 'Places'],
    tags: ['Maps', 'Geocoding', 'Places'],
    alternatives: ['mapbox', 'here-maps'],
  },
  {
    categoryId: 'maps',
    name: 'Mapbox',
    shortDescription: 'Custom mapping platform with powerful styling.',
    longDescription:
      'Mapbox offers highly customizable vector maps with a design studio and global data APIs.',
    website: 'https://www.mapbox.com',
    docs: 'https://docs.mapbox.com',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 88,
    features: ['Custom styling', 'Vector tiles', 'Navigation', 'Geocoding'],
    tags: ['Maps', 'Customizable', 'Navigation'],
    alternatives: ['google-maps', 'maplibre'],
  },
  {
    categoryId: 'maps',
    name: 'OpenStreetMap',
    shortDescription: 'Free, editable maps built by a global community.',
    longDescription:
      'OpenStreetMap is a free, collaborative map of the world that anyone can use and edit.',
    website: 'https://www.openstreetmap.org',
    docs: 'https://wiki.openstreetmap.org',
    github: 'openstreetmap/openstreetmap-website',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 90,
    features: ['Free map data', 'Community-edited', 'Open data', 'Self-hosted'],
    tags: ['Maps', 'Open data', 'Community'],
    alternatives: ['mapbox', 'maplibre'],
  },
  {
    categoryId: 'maps',
    name: 'MapLibre GL',
    shortDescription: 'Open-source map renderer with vector tiles.',
    longDescription:
      'MapLibre GL is a community-maintained, open-source map renderer for vector tiles and interactive maps.',
    website: 'https://maplibre.org',
    docs: 'https://maplibre.org/maplibre-gl-js/docs',
    github: 'maplibre/maplibre-gl-js',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 82,
    features: ['Vector tiles', 'Open source', 'Custom styling', 'Web and native'],
    tags: ['Maps', 'Open source', 'Vector tiles'],
    alternatives: ['mapbox', 'leaflet'],
  },
  {
    categoryId: 'maps',
    name: 'Leaflet',
    shortDescription: 'Lightweight, open-source mapping library.',
    longDescription:
      'Leaflet is a mobile-friendly, open-source JavaScript library for interactive maps with a huge plugin ecosystem.',
    website: 'https://leafletjs.com',
    docs: 'https://leafletjs.com/reference.html',
    github: 'Leaflet/Leaflet',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 85,
    features: ['Lightweight', 'Plugin ecosystem', 'Open source', 'Mobile friendly'],
    tags: ['Maps', 'Open source', 'Lightweight'],
    alternatives: ['maplibre', 'openstreetmap'],
  },
  {
    categoryId: 'maps',
    name: 'TomTom',
    shortDescription: 'Maps, routing, and traffic APIs for developers.',
    longDescription:
      'TomTom provides maps, routing, geofencing, and traffic APIs with extensive location intelligence.',
    website: 'https://www.tomtom.com',
    docs: 'https://developer.tomtom.com',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 76,
    features: ['Maps API', 'Routing', 'Traffic', 'Geofencing'],
    tags: ['Maps', 'Routing', 'Traffic'],
    alternatives: ['google-maps', 'here-maps'],
  },
  {
    categoryId: 'maps',
    name: 'HERE Technologies',
    shortDescription: 'Location data and mapping APIs for enterprises.',
    longDescription:
      'HERE provides mapping and location services with strong coverage for automotive and enterprise use cases.',
    website: 'https://www.here.com',
    docs: 'https://developer.here.com',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 78,
    features: ['Maps API', 'Routing', 'Geocoding', 'Location intelligence'],
    tags: ['Maps', 'Enterprise', 'Location'],
    alternatives: ['google-maps', 'tomtom'],
  },
  {
    categoryId: 'notifications',
    name: 'OneSignal',
    shortDescription: 'Multi-channel push, email, and SMS notifications.',
    longDescription:
      'OneSignal sends push notifications, email, SMS, and in-app messages to billions of users.',
    website: 'https://onesignal.com',
    docs: 'https://documentation.onesignal.com',
    github: 'OneSignal/OneSignal-Website-SDK',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 90,
    featured: true,
    features: ['Push notifications', 'In-app messages', 'Email', 'Segmentation'],
    tags: ['Push', 'SMS', 'Email'],
    alternatives: ['firebase-fcm', 'novu'],
  },
  {
    categoryId: 'notifications',
    name: 'Firebase Cloud Messaging',
    shortDescription: 'Free cross-platform push notifications from Google.',
    longDescription:
      'Firebase Cloud Messaging delivers free, reliable push notifications to Android, iOS, and web.',
    website: 'https://firebase.google.com/products/cloud-messaging',
    docs: 'https://firebase.google.com/docs/cloud-messaging',
    github: 'firebase/firebase-js-sdk',
    pricingModel: 'free',
    freeTier: true,
    openSource: false,
    popularityScore: 92,
    features: ['Push notifications', 'Topics', 'Targeted messages', 'Free'],
    tags: ['Push', 'Free', 'Cross-platform'],
    alternatives: ['onesignal', 'amazon-sns'],
  },
  {
    categoryId: 'notifications',
    name: 'Novu',
    shortDescription: 'Open-source notification infrastructure for multi-channel.',
    longDescription:
      'Novu is an open-source notification platform for managing email, SMS, push, and in-app via one API.',
    website: 'https://novu.co',
    docs: 'https://docs.novu.co',
    github: 'novuhq/novu',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 84,
    features: ['Multi-channel', 'In-app inbox', 'Workflows', 'Open source'],
    tags: ['Open source', 'Multi-channel', 'In-app'],
    alternatives: ['knock', 'courier'],
  },
  {
    categoryId: 'notifications',
    name: 'Pusher Beams',
    shortDescription: 'Managed push notifications with simple SDKs.',
    longDescription:
      'Pusher Beams is a hosted push notification service for iOS, Android, and web with delivery tracking.',
    website: 'https://pusher.com/beams',
    docs: 'https://pusher.com/docs/beams',
    github: 'pusher/push-notifications-web',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 78,
    features: ['Push notifications', 'Interests', 'Delivery tracking', 'SDKs'],
    tags: ['Push', 'SDK', 'Managed'],
    alternatives: ['onesignal', 'firebase-fcm'],
  },
  {
    categoryId: 'notifications',
    name: 'Knock',
    shortDescription: 'Notification infrastructure for product teams.',
    longDescription:
      'Knock is a notification infrastructure platform with workflows, preferences, and multi-channel delivery.',
    website: 'https://knock.app',
    docs: 'https://docs.knock.app',
    github: 'knocklabs/knock-js',
    pricingModel: 'subscription',
    freeTier: true,
    openSource: false,
    popularityScore: 76,
    features: ['Workflows', 'Preferences', 'Multi-channel', 'In-app feed'],
    tags: ['Notifications', 'Workflows', 'Multi-channel'],
    alternatives: ['novu', 'courier'],
  },
  {
    categoryId: 'notifications',
    name: 'Courier',
    shortDescription: 'API-first notification delivery to any channel.',
    longDescription:
      'Courier provides a notification API that routes messages to email, push, SMS, and chat channels.',
    website: 'https://www.courier.com',
    docs: 'https://www.courier.com/docs',
    github: 'trycourier/courier-node',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 74,
    features: ['Notification API', 'Channel routing', 'Templates', 'Digests'],
    tags: ['Notifications', 'API', 'Multi-channel'],
    alternatives: ['knock', 'novu'],
  },
  {
    categoryId: 'notifications',
    name: 'Amazon SNS',
    shortDescription: 'Managed pub/sub and push notification service from AWS.',
    longDescription:
      'Amazon SNS provides pub/sub messaging and push notifications to mobile devices and distributed systems.',
    website: 'https://aws.amazon.com/sns',
    docs: 'https://docs.aws.amazon.com/sns',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 80,
    features: ['Pub/Sub', 'Push notifications', 'Fan-out', 'AWS integration'],
    tags: ['Pub/Sub', 'Push', 'AWS'],
    alternatives: ['firebase-fcm', 'onesignal'],
  },
  {
    categoryId: 'testing',
    name: 'Jest',
    shortDescription: 'Delightful JavaScript testing framework with zero config.',
    longDescription:
      'Jest is the most popular JavaScript testing framework, featuring snapshots, code coverage, and a fast watch mode.',
    website: 'https://jestjs.io',
    docs: 'https://jestjs.io/docs',
    github: 'jestjs/jest',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 94,
    featured: true,
    features: ['Unit testing', 'Snapshots', 'Code coverage', 'Mocking'],
    tags: ['Testing', 'Unit', 'Open source'],
    alternatives: ['vitest', 'mocha'],
  },
  {
    categoryId: 'testing',
    name: 'Playwright',
    shortDescription: 'Cross-browser end-to-end testing by Microsoft.',
    longDescription:
      'Playwright automates Chromium, Firefox, and WebKit with a single API for reliable end-to-end tests.',
    website: 'https://playwright.dev',
    docs: 'https://playwright.dev/docs',
    github: 'microsoft/playwright',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 93,
    features: ['Cross-browser', 'End-to-end tests', 'Auto-waiting', 'Trace viewer'],
    tags: ['E2E testing', 'Cross-browser', 'Open source'],
    alternatives: ['cypress', 'puppeteer'],
  },
  {
    categoryId: 'testing',
    name: 'Cypress',
    shortDescription: 'Developer-friendly end-to-end testing framework.',
    longDescription:
      'Cypress makes end-to-end testing fast and fun with a rich interactive test runner.',
    website: 'https://www.cypress.io',
    docs: 'https://docs.cypress.io',
    github: 'cypress-io/cypress',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 90,
    features: ['End-to-end tests', 'Test runner', 'Time travel', 'Component testing'],
    tags: ['E2E testing', 'Framework', 'Open source'],
    alternatives: ['playwright', 'vitest'],
  },
  {
    categoryId: 'testing',
    name: 'Vitest',
    shortDescription: 'Vite-native unit testing with blazing-fast HMR.',
    longDescription:
      'Vitest is a Vite-native test framework offering near-instant feedback with full Jest compatibility.',
    website: 'https://vitest.dev',
    docs: 'https://vitest.dev/guide',
    github: 'vitest-dev/vitest',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 89,
    features: ['Fast HMR', 'Jest compatible', 'TypeScript', 'Coverage'],
    tags: ['Testing', 'Unit', 'Vite'],
    alternatives: ['jest', 'mocha'],
  },
  {
    categoryId: 'testing',
    name: 'Testing Library',
    shortDescription: 'Testing utilities for user-centric DOM queries.',
    longDescription:
      'Testing Library encourages testing UI the way users interact with it, working with React, Vue, and more.',
    website: 'https://testing-library.com',
    docs: 'https://testing-library.com/docs',
    github: 'testing-library/react-testing-library',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 87,
    features: ['User-centric queries', 'Accessibility', 'Framework agnostic', 'Open source'],
    tags: ['Testing', 'DOM', 'Open source'],
    alternatives: ['vitest', 'jest'],
  },
  {
    categoryId: 'testing',
    name: 'Puppeteer',
    shortDescription: 'Browser automation and testing by Google Chrome team.',
    longDescription:
      'Puppeteer provides a high-level API to control Chrome and Chromium for testing and automation.',
    website: 'https://pptr.dev',
    docs: 'https://pptr.dev/docs',
    github: 'puppeteer/puppeteer',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 84,
    features: ['Chrome automation', 'Screenshots', 'Scraping', 'Testing'],
    tags: ['Browser automation', 'Chrome', 'Open source'],
    alternatives: ['playwright', 'cypress'],
  },
  {
    categoryId: 'testing',
    name: 'Storybook',
    shortDescription: 'Frontend workshop for building UI components in isolation.',
    longDescription:
      'Storybook is the industry-standard UI development environment for building and testing components in isolation.',
    website: 'https://storybook.js.org',
    docs: 'https://storybook.js.org/docs',
    github: 'storybookjs/storybook',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 86,
    features: ['Component development', 'Testing', 'Addon ecosystem', 'Documentation'],
    tags: ['Component testing', 'UI', 'Open source'],
    alternatives: ['testing-library', 'cypress'],
  },
  {
    categoryId: 'devops',
    name: 'Terraform',
    shortDescription: 'Industry-standard infrastructure as code by HashiCorp.',
    longDescription:
      'Terraform lets you define and provision infrastructure across hundreds of providers with declarative config.',
    website: 'https://www.terraform.io',
    docs: 'https://developer.hashicorp.com/terraform',
    github: 'hashicorp/terraform',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 95,
    featured: true,
    features: ['Infrastructure as code', 'Declarative config', 'State management', 'Multi-cloud'],
    tags: ['IaC', 'Multi-cloud', 'Provisioning'],
    alternatives: ['pulumi', 'opentofu'],
  },
  {
    categoryId: 'devops',
    name: 'Pulumi',
    shortDescription: 'Infrastructure as code with real programming languages.',
    longDescription:
      'Pulumi lets you write infrastructure in TypeScript, Python, Go, or C# with full programmability.',
    website: 'https://www.pulumi.com',
    docs: 'https://www.pulumi.com/docs',
    github: 'pulumi/pulumi',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 86,
    features: ['Real languages', 'State management', 'Multi-cloud', 'Secrets'],
    tags: ['IaC', 'TypeScript', 'Multi-cloud'],
    alternatives: ['terraform', 'crossplane'],
  },
  {
    categoryId: 'devops',
    name: 'Ansible',
    shortDescription: 'Simple automation and configuration management.',
    longDescription:
      'Ansible automates provisioning, configuration management, and application deployment using YAML playbooks.',
    website: 'https://www.ansible.com',
    docs: 'https://docs.ansible.com',
    github: 'ansible/ansible',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 90,
    features: ['Playbooks', 'Configuration management', 'Agentless', 'Modules'],
    tags: ['Automation', 'Configuration', 'Open source'],
    alternatives: ['chef', 'terraform'],
  },
  {
    categoryId: 'devops',
    name: 'OpenTofu',
    shortDescription: 'Open-source fork of Terraform, Linux Foundation governed.',
    longDescription:
      'OpenTofu is an open-source, Linux Foundation-governed alternative to Terraform for infrastructure as code.',
    website: 'https://opentofu.org',
    docs: 'https://opentofu.org/docs',
    github: 'opentofu/opentofu',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 82,
    features: ['Terraform compatible', 'Open source', 'Community driven', 'State management'],
    tags: ['IaC', 'Open source', 'Provisioning'],
    alternatives: ['terraform', 'pulumi'],
  },
  {
    categoryId: 'devops',
    name: 'Crossplane',
    shortDescription: 'Cloud-native control plane for infrastructure provisioning.',
    longDescription:
      'Crossplane turns Kubernetes into a universal control plane for managing cloud infrastructure.',
    website: 'https://www.crossplane.io',
    docs: 'https://docs.crossplane.io',
    github: 'crossplane/crossplane',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 78,
    features: ['Control planes', 'Kubernetes native', 'Composition', 'Multi-cloud'],
    tags: ['IaC', 'Kubernetes', 'Control plane'],
    alternatives: ['pulumi', 'terraform'],
  },
  {
    categoryId: 'devops',
    name: 'Chef',
    shortDescription: 'Configuration management for infrastructure automation.',
    longDescription:
      'Chef automates configuration management and compliance across servers with code-based policies.',
    website: 'https://www.chef.io',
    docs: 'https://docs.chef.io',
    github: 'chef/chef',
    pricingModel: 'subscription',
    freeTier: false,
    openSource: true,
    popularityScore: 72,
    features: ['Configuration management', 'Cookbooks', 'Compliance', 'Automation'],
    tags: ['Configuration', 'Automation', 'Compliance'],
    alternatives: ['ansible', 'terraform'],
  },
  {
    categoryId: 'containerization',
    name: 'Docker',
    shortDescription: 'The industry standard for building and running containers.',
    longDescription:
      'Docker packages applications into portable containers that run anywhere, from laptops to production.',
    website: 'https://www.docker.com',
    docs: 'https://docs.docker.com',
    github: 'moby/moby',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 97,
    featured: true,
    features: ['Containerization', 'Images', 'Compose', 'Registry'],
    tags: ['Containers', 'Packaging', 'Open source'],
    alternatives: ['podman', 'containerd'],
  },
  {
    categoryId: 'containerization',
    name: 'Kubernetes',
    shortDescription: 'The standard for container orchestration at scale.',
    longDescription:
      'Kubernetes automates deployment, scaling, and operations of containerized applications across clusters.',
    website: 'https://kubernetes.io',
    docs: 'https://kubernetes.io/docs',
    github: 'kubernetes/kubernetes',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 95,
    features: ['Orchestration', 'Scaling', 'Self-healing', 'Service discovery'],
    tags: ['Orchestration', 'Containers', 'Open source'],
    alternatives: ['docker-swarm', 'rancher'],
  },
  {
    categoryId: 'containerization',
    name: 'Podman',
    shortDescription: 'Daemonless container engine with Docker compatibility.',
    longDescription:
      'Podman is a daemonless, rootless container engine that is a drop-in replacement for Docker.',
    website: 'https://podman.io',
    docs: 'https://podman.io/docs',
    github: 'containers/podman',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 84,
    features: ['Daemonless', 'Rootless', 'Docker compatible', 'Pod support'],
    tags: ['Containers', 'Open source', 'Rootless'],
    alternatives: ['docker', 'containerd'],
  },
  {
    categoryId: 'containerization',
    name: 'containerd',
    shortDescription: 'Industry-standard container runtime from CNCF.',
    longDescription:
      'containerd is a robust, industry-standard container runtime focused on simplicity and portability.',
    website: 'https://containerd.io',
    docs: 'https://containerd.io/docs',
    github: 'containerd/containerd',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 86,
    features: ['Container runtime', 'CNCF', 'OCI compatible', 'Snapshotter'],
    tags: ['Runtime', 'Containers', 'CNCF'],
    alternatives: ['podman', 'docker'],
  },
  {
    categoryId: 'containerization',
    name: 'Helm',
    shortDescription: 'The package manager for Kubernetes.',
    longDescription:
      'Helm packages Kubernetes applications into charts, making deployment and upgrades reproducible.',
    website: 'https://helm.sh',
    docs: 'https://helm.sh/docs',
    github: 'helm/helm',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 88,
    features: ['Charts', 'Releases', 'Templating', 'Rollbacks'],
    tags: ['Kubernetes', 'Packaging', 'Open source'],
    alternatives: ['kustomize', 'rancher'],
  },
  {
    categoryId: 'containerization',
    name: 'Rancher',
    shortDescription: 'Complete Kubernetes management platform.',
    longDescription:
      'Rancher manages Kubernetes clusters anywhere — on-prem, cloud, or edge — from a single UI.',
    website: 'https://www.rancher.com',
    docs: 'https://docs.rancher.com',
    github: 'rancher/rancher',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 80,
    features: ['Cluster management', 'Multi-cluster', 'UI', 'CI/CD integration'],
    tags: ['Kubernetes', 'Management', 'Open source'],
    alternatives: ['k3s', 'rancher'],
  },
  {
    categoryId: 'containerization',
    name: 'K3s',
    shortDescription: 'Lightweight certified Kubernetes for edge and IoT.',
    longDescription:
      'K3s is a lightweight, certified Kubernetes distribution perfect for edge, dev, and small clusters.',
    website: 'https://k3s.io',
    docs: 'https://docs.k3s.io',
    github: 'k3s-io/k3s',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 82,
    features: ['Lightweight', 'Edge ready', 'Single binary', 'Certified'],
    tags: ['Kubernetes', 'Lightweight', 'Edge'],
    alternatives: ['rancher', 'kubernetes'],
  },
  {
    categoryId: 'serverless',
    name: 'AWS Lambda',
    shortDescription: 'The original serverless function platform at massive scale.',
    longDescription:
      'AWS Lambda runs code in response to events without provisioning servers, scaling automatically.',
    website: 'https://aws.amazon.com/lambda',
    docs: 'https://docs.aws.amazon.com/lambda',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 96,
    featured: true,
    features: ['Functions as a service', 'Event driven', 'Auto scaling', 'Pay per invoke'],
    tags: ['Functions', 'AWS', 'Event driven'],
    alternatives: ['cloudflare-workers', 'google-cloud-functions'],
  },
  {
    categoryId: 'serverless',
    name: 'Cloudflare Workers',
    shortDescription: 'Serverless code on the global edge network.',
    longDescription:
      'Cloudflare Workers run JavaScript, Wasm, and Python on Cloudflare\u2019s edge in 300+ cities.',
    website: 'https://workers.cloudflare.com',
    docs: 'https://developers.cloudflare.com/workers',
    github: 'cloudflare/workers-sdk',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 90,
    features: ['Edge compute', 'Workers KV', 'Durable Objects', 'Zero cold starts'],
    tags: ['Edge', 'Functions', 'Fast'],
    alternatives: ['aws-lambda', 'deno-deploy'],
  },
  {
    categoryId: 'serverless',
    name: 'Azure Functions',
    shortDescription: 'Event-driven serverless compute on Microsoft Azure.',
    longDescription:
      'Azure Functions runs event-driven code in the cloud with deep Azure integration.',
    website: 'https://azure.microsoft.com/products/functions',
    docs: 'https://learn.microsoft.com/azure/azure-functions',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 86,
    features: ['Functions as a service', 'Triggers', 'Durable functions', 'Azure integration'],
    tags: ['Functions', 'Azure', 'Event driven'],
    alternatives: ['aws-lambda', 'google-cloud-functions'],
  },
  {
    categoryId: 'serverless',
    name: 'Google Cloud Functions',
    shortDescription: 'Single-purpose functions on Google Cloud.',
    longDescription:
      'Google Cloud Functions runs event-driven serverless code with simple deployment from Git.',
    website: 'https://cloud.google.com/functions',
    docs: 'https://cloud.google.com/functions/docs',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 84,
    features: ['Functions as a service', 'Event triggers', 'Gen2 runtime', 'GCP integration'],
    tags: ['Functions', 'GCP', 'Event driven'],
    alternatives: ['aws-lambda', 'azure-functions'],
  },
  {
    categoryId: 'serverless',
    name: 'Vercel Functions',
    shortDescription: 'Serverless and edge functions for frontend platforms.',
    longDescription:
      'Vercel Functions provide serverless compute for Next.js and frontend apps with automatic region selection.',
    website: 'https://vercel.com/docs/functions',
    docs: 'https://vercel.com/docs/functions',
    github: 'vercel/vercel',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 88,
    features: ['Serverless functions', 'Edge functions', 'Automatic regions', 'Next.js integration'],
    tags: ['Functions', 'Edge', 'Next.js'],
    alternatives: ['netlify-functions', 'cloudflare-workers'],
  },
  {
    categoryId: 'serverless',
    name: 'Netlify Functions',
    shortDescription: 'Serverless functions for static and dynamic sites.',
    longDescription:
      'Netlify Functions add serverless compute to Netlify sites with Git-based deployment.',
    website: 'https://www.netlify.com/products/functions',
    docs: 'https://docs.netlify.com/functions',
    github: 'netlify/netlify',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 82,
    features: ['Serverless functions', 'Background functions', 'Blobs', 'Git deploys'],
    tags: ['Functions', 'Static sites', 'Serverless'],
    alternatives: ['vercel-functions', 'cloudflare-workers'],
  },
  {
    categoryId: 'serverless',
    name: 'Deno Deploy',
    shortDescription: 'Edge-first serverless platform for Deno and JavaScript.',
    longDescription:
      'Deno Deploy runs Deno, JavaScript, and TypeScript at the edge with global distribution.',
    website: 'https://deno.com/deploy',
    docs: 'https://docs.deno.com/deploy',
    github: 'denoland/deploy_feedback',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 76,
    features: ['Edge compute', 'Deno runtime', 'Global distribution', 'NPM support'],
    tags: ['Edge', 'Deno', 'Functions'],
    alternatives: ['cloudflare-workers', 'aws-lambda'],
  },
  {
    categoryId: 'ci-cd',
    name: 'GitHub Actions',
    shortDescription: 'CI/CD integrated directly with GitHub.',
    longDescription:
      'GitHub Actions automates build, test, and deploy workflows right where your code lives.',
    website: 'https://github.com/features/actions',
    docs: 'https://docs.github.com/actions',
    github: 'actions/runner',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 96,
    featured: true,
    features: ['Workflows', 'Matrix builds', 'Marketplace', 'Self-hosted runners'],
    tags: ['CI/CD', 'GitHub', 'Workflows'],
    alternatives: ['gitlab-ci', 'circleci'],
  },
  {
    categoryId: 'ci-cd',
    name: 'GitLab CI/CD',
    shortDescription: 'Integrated CI/CD pipelines with GitLab DevOps.',
    longDescription:
      'GitLab CI/CD provides built-in pipelines, environments, and deployment automation across the GitLab platform.',
    website: 'https://docs.gitlab.com/ee/ci',
    docs: 'https://docs.gitlab.com/ee/ci',
    github: 'gitlabhq/gitlabhq',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 88,
    features: ['Pipelines', 'Auto DevOps', 'Environments', 'Review apps'],
    tags: ['CI/CD', 'GitLab', 'Pipelines'],
    alternatives: ['github-actions', 'jenkins'],
  },
  {
    categoryId: 'ci-cd',
    name: 'CircleCI',
    shortDescription: 'Cloud CI/CD with fast, parallel pipelines.',
    longDescription:
      'CircleCI delivers fast, reliable CI/CD with powerful parallelism and a huge orb registry.',
    website: 'https://circleci.com',
    docs: 'https://circleci.com/docs',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 84,
    features: ['Parallel jobs', 'Orbs', 'Caching', 'Insights'],
    tags: ['CI/CD', 'Cloud', 'Pipelines'],
    alternatives: ['github-actions', 'buildkite'],
  },
  {
    categoryId: 'ci-cd',
    name: 'Jenkins',
    shortDescription: 'The leading open-source automation server.',
    longDescription:
      'Jenkins is a self-hosted automation server with a vast plugin ecosystem for CI/CD and beyond.',
    website: 'https://www.jenkins.io',
    docs: 'https://www.jenkins.io/doc',
    github: 'jenkinsci/jenkins',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 86,
    features: ['Self-hosted', 'Plugin ecosystem', 'Pipeline DSL', 'Distributed builds'],
    tags: ['CI/CD', 'Self-hosted', 'Open source'],
    alternatives: ['gitlab-ci', 'circleci'],
  },
  {
    categoryId: 'ci-cd',
    name: 'Buildkite',
    shortDescription: 'CI/CD that runs on your own infrastructure.',
    longDescription:
      'Buildkite combines cloud orchestration with your own build agents for full control and performance.',
    website: 'https://buildkite.com',
    docs: 'https://buildkite.com/docs',
    pricingModel: 'subscription',
    freeTier: false,
    openSource: false,
    popularityScore: 78,
    features: ['Your own agents', 'Pipelines', 'Parallelism', 'Test analytics'],
    tags: ['CI/CD', 'Self-hosted agents', 'Pipelines'],
    alternatives: ['circleci', 'github-actions'],
  },
  {
    categoryId: 'ci-cd',
    name: 'Travis CI',
    shortDescription: 'Cloud CI/CD with a simple configuration.',
    longDescription:
      'Travis CI was one of the first hosted CI services, providing simple .travis.yml-based pipelines.',
    website: 'https://www.travis-ci.com',
    docs: 'https://docs.travis-ci.com',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 72,
    features: ['Simple config', 'Matrix builds', 'Hosted', 'Deployments'],
    tags: ['CI/CD', 'Hosted', 'Simple'],
    alternatives: ['github-actions', 'circleci'],
  },
  {
    categoryId: 'ci-cd',
    name: 'Bitbucket Pipelines',
    shortDescription: 'CI/CD built into Bitbucket Cloud.',
    longDescription:
      'Bitbucket Pipelines runs CI/CD in the cloud directly from Bitbucket repositories.',
    website: 'https://bitbucket.org/product/features/pipelines',
    docs: 'https://support.atlassian.com/bitbucket-cloud/docs/getting-started-with-bitbucket-pipelines',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 74,
    features: ['Cloud CI', 'Deployments', 'Docker builds', 'Bitbucket integration'],
    tags: ['CI/CD', 'Bitbucket', 'Cloud'],
    alternatives: ['github-actions', 'gitlab-ci'],
  },
  {
    categoryId: 'video-apis',
    name: 'Mux',
    shortDescription: 'Video API for streaming, encoding, and analytics.',
    longDescription:
      'Mux provides a complete video API for encoding, streaming, and playback analytics.',
    website: 'https://www.mux.com',
    docs: 'https://docs.mux.com',
    github: 'muxinc/mux-node',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 88,
    featured: true,
    features: ['Streaming', 'Encoding', 'Player SDK', 'Analytics'],
    tags: ['Streaming', 'Encoding', 'Player'],
    alternatives: ['cloudflare-stream', 'api-video'],
  },
  {
    categoryId: 'video-apis',
    name: 'Cloudflare Stream',
    shortDescription: 'End-to-end video streaming with global delivery.',
    longDescription:
      'Cloudflare Stream handles encoding, delivery, and playback with global edge streaming.',
    website: 'https://developers.cloudflare.com/stream',
    docs: 'https://developers.cloudflare.com/stream',
    github: 'cloudflare/workers-sdk',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 84,
    features: ['Video encoding', 'Global delivery', 'Live streaming', 'Player'],
    tags: ['Streaming', 'CDN', 'Encoding'],
    alternatives: ['mux', 'bunny-stream'],
  },
  {
    categoryId: 'video-apis',
    name: 'api.video',
    shortDescription: 'Developer-first video API for live and on-demand.',
    longDescription:
      'api.video offers a straightforward video API for live streaming and on-demand hosting.',
    website: 'https://api.video',
    docs: 'https://docs.api.video',
    github: 'apivideo/api.video-nodejs-client',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 78,
    features: ['Live streaming', 'VOD', 'SDKs', 'Analytics'],
    tags: ['Live streaming', 'VOD', 'SDK'],
    alternatives: ['mux', 'cloudflare-stream'],
  },
  {
    categoryId: 'video-apis',
    name: 'YouTube IFrame API',
    shortDescription: 'Embed and control YouTube videos with a player API.',
    longDescription:
      'The YouTube IFrame API embeds YouTube players and gives you full control over playback.',
    website: 'https://developers.google.com/youtube/iframe_api_reference',
    docs: 'https://developers.google.com/youtube/iframe_api_reference',
    pricingModel: 'free',
    freeTier: true,
    openSource: false,
    popularityScore: 86,
    features: ['Embedding', 'Playback control', 'Free', 'Player events'],
    tags: ['Embed', 'Free', 'Player'],
    alternatives: ['vimeo', 'mux'],
  },
  {
    categoryId: 'video-apis',
    name: 'Vimeo',
    shortDescription: 'Professional video hosting with a developer API.',
    longDescription:
      'Vimeo provides high-quality video hosting with a developer API and customizable players.',
    website: 'https://developer.vimeo.com',
    docs: 'https://developer.vimeo.com/api',
    pricingModel: 'subscription',
    freeTier: false,
    openSource: false,
    popularityScore: 80,
    features: ['Video hosting', 'Developer API', 'Custom players', 'Analytics'],
    tags: ['Hosting', 'Player', 'API'],
    alternatives: ['youtube-embed', 'api-video'],
  },
  {
    categoryId: 'video-apis',
    name: 'Bunny Stream',
    shortDescription: 'Affordable video streaming with global delivery.',
    longDescription:
      'Bunny Stream offers simple, low-cost video hosting, encoding, and delivery.',
    website: 'https://bunny.net/stream',
    docs: 'https://docs.bunny.net/stream',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 76,
    features: ['Video hosting', 'Encoding', 'Global delivery', 'Low cost'],
    tags: ['Streaming', 'Affordable', 'CDN'],
    alternatives: ['cloudflare-stream', 'api-video'],
  },
  {
    categoryId: 'video-apis',
    name: 'Wowza',
    shortDescription: 'Video streaming platform for live and on-demand.',
    longDescription:
      'Wowza is a flexible streaming platform for live, low-latency, and on-demand video at scale.',
    website: 'https://www.wowza.com',
    docs: 'https://www.wowza.com/docs',
    pricingModel: 'subscription',
    freeTier: false,
    openSource: false,
    popularityScore: 78,
    features: ['Live streaming', 'Low latency', 'Transcoding', 'Enterprise'],
    tags: ['Live streaming', 'Transcoding', 'Enterprise'],
    alternatives: ['mux', 'cloudflare-stream'],
  },
  {
    categoryId: 'cdn',
    name: 'Cloudflare',
    shortDescription: 'Global CDN with edge computing and DDoS protection.',
    longDescription:
      'Cloudflare is a massive global CDN with edge computing, caching, and enterprise-grade security.',
    website: 'https://www.cloudflare.com',
    docs: 'https://developers.cloudflare.com',
    github: 'cloudflare/workers-sdk',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 95,
    featured: true,
    features: ['Global CDN', 'DDoS protection', 'Caching', 'Edge compute'],
    tags: ['Edge', 'DDoS protection', 'Caching'],
    alternatives: ['fastly', 'cloudfront'],
  },
  {
    categoryId: 'cdn',
    name: 'Fastly',
    shortDescription: 'Real-time CDN with programmable edge.',
    longDescription:
      'Fastly delivers high-performance content with real-time cache purging and programmable edge logic.',
    website: 'https://www.fastly.com',
    docs: 'https://developer.fastly.com',
    github: 'fastly/fastly-js',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 82,
    features: ['Real-time purge', 'Programmable edge', 'Image optimization', 'Security'],
    tags: ['Edge', 'Realtime', 'Image optimization'],
    alternatives: ['cloudflare', 'akamai'],
  },
  {
    categoryId: 'cdn',
    name: 'Amazon CloudFront',
    shortDescription: 'AWS global content delivery network.',
    longDescription:
      'Amazon CloudFront is a fast content delivery network that integrates deeply with AWS services.',
    website: 'https://aws.amazon.com/cloudfront',
    docs: 'https://docs.aws.amazon.com/cloudfront',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 90,
    features: ['Global CDN', 'AWS integration', 'Lambda edge', 'Security'],
    tags: ['CDN', 'AWS', 'Edge'],
    alternatives: ['cloudflare', 'azure-front-door'],
  },
  {
    categoryId: 'cdn',
    name: 'Bunny CDN',
    shortDescription: 'Affordable, high-performance CDN with per-GB pricing.',
    longDescription:
      'Bunny CDN delivers high performance at low cost with simple, transparent per-GB pricing.',
    website: 'https://bunny.net',
    docs: 'https://docs.bunny.net',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 84,
    features: ['Global network', 'Per-GB pricing', 'Edge storage', 'Image optimization'],
    tags: ['Affordable', 'Caching', 'Per-GB'],
    alternatives: ['cloudflare', 'keycdn'],
  },
  {
    categoryId: 'cdn',
    name: 'Akamai',
    shortDescription: 'Enterprise CDN and edge security platform.',
    longDescription:
      'Akamai is one of the world\u2019s largest CDNs, serving enterprise-grade delivery and security.',
    website: 'https://www.akamai.com',
    docs: 'https://techdocs.akamai.com',
    pricingModel: 'subscription',
    freeTier: false,
    openSource: false,
    popularityScore: 86,
    features: ['Global delivery', 'Enterprise security', 'Media delivery', 'Edge DNS'],
    tags: ['CDN', 'Enterprise', 'Security'],
    alternatives: ['cloudflare', 'fastly'],
  },
  {
    categoryId: 'cdn',
    name: 'Azure Front Door',
    shortDescription: 'Microsoft\u2019s global CDN and application delivery.',
    longDescription:
      'Azure Front Door combines global CDN with application acceleration and WAF protection.',
    website: 'https://azure.microsoft.com/products/frontdoor',
    docs: 'https://learn.microsoft.com/azure/frontdoor',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 78,
    features: ['Global CDN', 'WAF', 'Acceleration', 'Azure integration'],
    tags: ['CDN', 'Azure', 'WAF'],
    alternatives: ['cloudfront', 'cloudflare'],
  },
  {
    categoryId: 'cdn',
    name: 'KeyCDN',
    shortDescription: 'Fast, straightforward CDN with real-time analytics.',
    longDescription:
      'KeyCDN is a simple, high-performance CDN with instant setup and real-time analytics.',
    website: 'https://www.keycdn.com',
    docs: 'https://www.keycdn.com/support',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 76,
    features: ['Global network', 'Real-time analytics', 'Instant setup', 'Cache rules'],
    tags: ['CDN', 'Affordable', 'Analytics'],
    alternatives: ['bunny', 'cloudflare'],
  },
];

export const opsProviders = buildProviders(rows);
