import { buildProviders, type SeedProvider } from './helpers';

const rows: SeedProvider[] = [
  {
    categoryId: 'ai-models',
    name: 'Hugging Face',
    shortDescription: 'The hub for open-source models, datasets, and inference.',
    longDescription:
      'Hugging Face hosts hundreds of thousands of open-source models, datasets, and spaces, with managed inference endpoints.',
    website: 'https://huggingface.co',
    docs: 'https://huggingface.co/docs',
    github: 'huggingface/transformers',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 95,
    featured: true,
    features: ['Model hub', 'Inference endpoints', 'Transformers library', 'Datasets'],
    tags: ['Models', 'Open source', 'Inference'],
    alternatives: ['replicate', 'together-ai'],
  },
  {
    categoryId: 'ai-models',
    name: 'Replicate',
    shortDescription: 'Run and scale open-source AI models with one API.',
    longDescription:
      'Replicate lets you run and deploy open-source AI models with a single API, from image generation to language models.',
    website: 'https://replicate.com',
    docs: 'https://replicate.com/docs',
    github: 'replicate/replicate-javascript',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 88,
    features: ['Model API', 'Serverless inference', 'Fine-tuning', 'Webhooks'],
    tags: ['Models', 'API', 'Serverless'],
    alternatives: ['fal', 'together-ai'],
  },
  {
    categoryId: 'ai-models',
    name: 'Together AI',
    shortDescription: 'Cloud platform for running and fine-tuning open-source LLMs.',
    longDescription:
      'Together AI provides fast, low-cost inference and fine-tuning for open-source models like Llama and Mistral.',
    website: 'https://www.together.ai',
    docs: 'https://docs.together.ai',
    github: 'togethercomputer/Together',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 82,
    features: ['LLM inference', 'Fine-tuning', 'Model routing', 'GPU clusters'],
    tags: ['LLM', 'Inference', 'Fine-tuning'],
    alternatives: ['groq', 'openrouter'],
  },
  {
    categoryId: 'ai-models',
    name: 'OpenRouter',
    shortDescription: 'Unified API for 300+ models with one integration.',
    longDescription:
      'OpenRouter is a single API gateway to hundreds of AI models, letting you route, compare, and switch models easily.',
    website: 'https://openrouter.ai',
    docs: 'https://openrouter.ai/docs',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 86,
    features: ['Multi-model API', 'Model routing', 'Unified billing', 'Fallbacks'],
    tags: ['Models', 'Gateway', 'API'],
    alternatives: ['together-ai', 'groq'],
  },
  {
    categoryId: 'ai-models',
    name: 'Groq',
    shortDescription: 'Ultra-fast AI inference with custom LPU hardware.',
    longDescription:
      'Groq runs open and proprietary models on its Language Processing Units, delivering industry-leading inference speed.',
    website: 'https://groq.com',
    docs: 'https://console.groq.com/docs',
    github: 'groq/groq-python',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 84,
    features: ['Fast inference', 'Open models', 'Chat completions', 'Function calling'],
    tags: ['Inference', 'Fast', 'Open models'],
    alternatives: ['together-ai', 'fireworks'],
  },
  {
    categoryId: 'ai-models',
    name: 'fal.ai',
    shortDescription: 'Serverless platform for image, video, and audio models.',
    longDescription:
      'fal.ai offers low-latency, serverless inference for generative media models with simple REST APIs.',
    website: 'https://fal.ai',
    docs: 'https://fal.ai/docs',
    github: 'fal-ai/fal',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 80,
    features: ['Media generation', 'Serverless inference', 'Queues', 'Webhooks'],
    tags: ['Images', 'Video', 'Serverless'],
    alternatives: ['replicate', 'fireworks'],
  },
  {
    categoryId: 'ai-models',
    name: 'Fireworks AI',
    shortDescription: 'Fast and efficient open-weight model inference platform.',
    longDescription:
      'Fireworks AI serves open-weight models at production scale with fast inference and fine-tuning options.',
    website: 'https://fireworks.ai',
    docs: 'https://docs.fireworks.ai',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 78,
    features: ['Open-weight models', 'Fast inference', 'Fine-tuning', 'Structured output'],
    tags: ['LLM', 'Inference', 'Open models'],
    alternatives: ['groq', 'together-ai'],
  },
  {
    categoryId: 'llm',
    name: 'OpenAI',
    shortDescription: 'GPT models and the industry-standard LLM API.',
    longDescription:
      'OpenAI provides GPT-4o, GPT-4o mini, and o-series models with a widely adopted API, function calling, and tooling.',
    website: 'https://openai.com',
    docs: 'https://platform.openai.com/docs',
    github: 'openai/openai-node',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 99,
    featured: true,
    features: ['GPT models', 'Function calling', 'Structured output', 'Assistants API'],
    tags: ['LLM', 'API', 'GPT'],
    alternatives: ['anthropic', 'google-gemini'],
  },
  {
    categoryId: 'llm',
    name: 'Anthropic',
    shortDescription: 'Claude models with strong reasoning and safety.',
    longDescription:
      'Anthropic builds Claude, a family of LLMs known for strong reasoning, long context, and safety-focused design.',
    website: 'https://www.anthropic.com',
    docs: 'https://docs.anthropic.com',
    github: 'anthropics/anthropic-sdk-typescript',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 95,
    features: ['Claude models', 'Long context', 'Tool use', 'Computer use'],
    tags: ['LLM', 'Claude', 'Reasoning'],
    alternatives: ['openai', 'google-gemini'],
  },
  {
    categoryId: 'llm',
    name: 'Google Gemini',
    shortDescription: 'Google\u2019s multimodal LLM family with broad capabilities.',
    longDescription:
      'Google Gemini offers multimodal models with text, image, audio, and video understanding plus strong tool support.',
    website: 'https://ai.google.dev',
    docs: 'https://ai.google.dev/docs',
    github: 'google-gemini/generative-ai-js',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 92,
    features: ['Multimodal', 'Long context', 'Function calling', 'Free tier'],
    tags: ['LLM', 'Multimodal', 'Google'],
    alternatives: ['openai', 'anthropic'],
  },
  {
    categoryId: 'llm',
    name: 'Mistral',
    shortDescription: 'Open-weight LLMs with strong performance per dollar.',
    longDescription:
      'Mistral offers efficient open-weight models and a hosted API with competitive pricing.',
    website: 'https://mistral.ai',
    docs: 'https://docs.mistral.ai',
    github: 'mistralai/client-python',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: true,
    popularityScore: 85,
    features: ['Open-weight models', 'Chat API', 'Function calling', 'Fine-tuning'],
    tags: ['LLM', 'Open source', 'Efficient'],
    alternatives: ['openai', 'cohere'],
  },
  {
    categoryId: 'llm',
    name: 'Cohere',
    shortDescription: 'Enterprise LLM APIs with strong retrieval and grounding.',
    longDescription:
      'Cohere provides LLM APIs tuned for enterprise RAG, classification, and embeddings use cases.',
    website: 'https://cohere.com',
    docs: 'https://docs.cohere.com',
    github: 'cohere-ai/cohere-typescript',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 80,
    features: ['RAG', 'Embeddings', 'Classification', 'Command models'],
    tags: ['LLM', 'Enterprise', 'RAG'],
    alternatives: ['mistral', 'openai'],
  },
  {
    categoryId: 'llm',
    name: 'DeepSeek',
    shortDescription: 'Open-weight reasoning models with low-cost inference.',
    longDescription:
      'DeepSeek offers powerful open-weight models including strong reasoning models at very low API prices.',
    website: 'https://www.deepseek.com',
    docs: 'https://api-docs.deepseek.com',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: true,
    popularityScore: 83,
    features: ['Reasoning models', 'Low cost', 'Open weights', 'Long context'],
    tags: ['LLM', 'Reasoning', 'Open source'],
    alternatives: ['openai', 'mistral'],
  },
  {
    categoryId: 'llm',
    name: 'AI21 Labs',
    shortDescription: 'Jamba models with long context and enterprise features.',
    longDescription:
      'AI21 Labs builds the Jamba family of hybrid LLMs, combining transformer and state-space architectures.',
    website: 'https://www.ai21.com',
    docs: 'https://docs.ai21.com',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 74,
    features: ['Jamba models', 'Long context', 'Enterprise features', 'Foundation models'],
    tags: ['LLM', 'Enterprise', 'Long context'],
    alternatives: ['cohere', 'mistral'],
  },
  {
    categoryId: 'chat',
    name: 'Sendbird',
    shortDescription: 'Complete in-app chat and messaging platform.',
    longDescription:
      'Sendbird provides SDKs and infrastructure for in-app chat, including moderation, push notifications, and AI features.',
    website: 'https://sendbird.com',
    docs: 'https://sendbird.com/docs',
    github: 'sendbird/sendbird-platform-sdk-javascript',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 84,
    featured: true,
    features: ['In-app chat', 'Moderation', 'Push notifications', 'AI assistant'],
    tags: ['Chat', 'Messaging', 'SDK'],
    alternatives: ['getstream', 'twilio-conversations'],
  },
  {
    categoryId: 'chat',
    name: 'Stream Chat',
    shortDescription: 'Feed and chat APIs with 10 billion daily API calls.',
    longDescription:
      'GetStream powers chat and activity feeds at scale, with flexible SDKs and fully managed infrastructure.',
    website: 'https://getstream.io',
    docs: 'https://getstream.io/chat/docs',
    github: 'GetStream/stream-chat-js',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 86,
    features: ['Chat API', 'Activity feeds', 'Moderation', 'Realtime'],
    tags: ['Chat', 'Feeds', 'Realtime'],
    alternatives: ['sendbird', 'ably'],
  },
  {
    categoryId: 'chat',
    name: 'PubNub',
    shortDescription: 'Realtime infrastructure for chat, presence, and pub/sub.',
    longDescription:
      'PubNub is a global data stream network for realtime apps, chat, presence, and pub/sub messaging.',
    website: 'https://www.pubnub.com',
    docs: 'https://www.pubnub.com/docs',
    github: 'pubnub/javascript',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 78,
    features: ['Pub/Sub', 'Presence', 'Chat components', 'Global network'],
    tags: ['Realtime', 'Pub/Sub', 'Presence'],
    alternatives: ['ably', 'getstream'],
  },
  {
    categoryId: 'chat',
    name: 'Ably',
    shortDescription: 'Realtime messaging and event delivery at global scale.',
    longDescription:
      'Ably delivers realtime messaging, presence, and event streaming with predictable global latency.',
    website: 'https://ably.com',
    docs: 'https://ably.com/docs',
    github: 'ably/ably-js',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 82,
    features: ['Realtime messaging', 'Presence', 'Channels', 'Global edge'],
    tags: ['Realtime', 'Messaging', 'Pub/Sub'],
    alternatives: ['pubnub', 'getstream'],
  },
  {
    categoryId: 'chat',
    name: 'Twilio Conversations',
    shortDescription: 'Programmable multi-channel messaging conversations.',
    longDescription:
      'Twilio Conversations is an API for multi-channel messaging across in-app chat, SMS, and WhatsApp from one conversation.',
    website: 'https://www.twilio.com/conversations',
    docs: 'https://www.twilio.com/docs/conversations',
    github: 'twilio/twilio-node',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 80,
    features: ['Multi-channel', 'In-app chat', 'SMS', 'WhatsApp'],
    tags: ['Messaging', 'Multi-channel', 'Twilio'],
    alternatives: ['sendbird', 'getstream'],
  },
  {
    categoryId: 'chat',
    name: 'Agora Chat',
    shortDescription: 'SDKs for chat, voice, and video built for scale.',
    longDescription:
      'Agora provides realtime engagement SDKs including chat, voice, and video with global SD-RTN coverage.',
    website: 'https://www.agora.io',
    docs: 'https://docs.agora.io',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 76,
    features: ['Chat SDK', 'Voice and video', 'Realtime', 'Global network'],
    tags: ['Chat', 'Realtime', 'SDK'],
    alternatives: ['getstream', 'sendbird'],
  },
  {
    categoryId: 'voice',
    name: 'ElevenLabs',
    shortDescription: 'AI text-to-speech with ultra-realistic voices.',
    longDescription:
      'ElevenLabs is the leading AI voice platform with realistic text-to-speech, voice cloning, and dubbing.',
    website: 'https://elevenlabs.io',
    docs: 'https://elevenlabs.io/docs',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 88,
    featured: true,
    features: ['Text-to-speech', 'Voice cloning', 'Dubbing', 'Sound effects'],
    tags: ['TTS', 'AI voice', 'Realistic'],
    alternatives: ['openai-whisper', 'speechmatics'],
  },
  {
    categoryId: 'voice',
    name: 'OpenAI Whisper',
    shortDescription: 'Open-source speech recognition with multilingual support.',
    longDescription:
      'Whisper is OpenAI\u2019s open-source speech recognition model supporting dozens of languages, available via API.',
    website: 'https://openai.com/index/whisper',
    docs: 'https://platform.openai.com/docs/guides/speech-to-text',
    github: 'openai/whisper',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 90,
    features: ['Speech-to-text', 'Multilingual', 'Translation', 'Open source'],
    tags: ['STT', 'Open source', 'Multilingual'],
    alternatives: ['assemblyai', 'deepgram'],
  },
  {
    categoryId: 'voice',
    name: 'AssemblyAI',
    shortDescription: 'Speech-to-text API with speaker labels and insights.',
    longDescription:
      'AssemblyAI provides accurate speech-to-text with features like speaker detection, sentiment, and topic extraction.',
    website: 'https://www.assemblyai.com',
    docs: 'https://www.assemblyai.com/docs',
    github: 'AssemblyAI/assemblyai-node-sdk',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 85,
    features: ['Speech-to-text', 'Speaker labels', 'Sentiment analysis', 'Auto chapters'],
    tags: ['STT', 'API', 'Insights'],
    alternatives: ['deepgram', 'whisper'],
  },
  {
    categoryId: 'voice',
    name: 'Deepgram',
    shortDescription: 'Realtime speech-to-text with low latency and high accuracy.',
    longDescription:
      'Deepgram offers realtime speech-to-text and text-to-speech with very low latency and domain-specific models.',
    website: 'https://deepgram.com',
    docs: 'https://deepgram.com/docs',
    github: 'deepgram/deepgram-node-sdk',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 83,
    features: ['Realtime STT', 'Text-to-speech', 'Low latency', 'Custom models'],
    tags: ['STT', 'Realtime', 'Low latency'],
    alternatives: ['assemblyai', 'whisper'],
  },
  {
    categoryId: 'voice',
    name: 'Twilio Voice',
    shortDescription: 'Programmable voice for calls, IVR, and telephony.',
    longDescription:
      'Twilio Voice lets you build and scale voice applications with programmable calling, IVR, and global numbers.',
    website: 'https://www.twilio.com/voice',
    docs: 'https://www.twilio.com/docs/voice',
    github: 'twilio/twilio-node',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 87,
    features: ['Programmable voice', 'IVR', 'Global numbers', 'SIP'],
    tags: ['Telephony', 'Calls', 'IVR'],
    alternatives: ['vonage', 'twilio-conversations'],
  },
  {
    categoryId: 'voice',
    name: 'Vonage',
    shortDescription: 'Voice, messaging, and video APIs for communications.',
    longDescription:
      'Vonage provides APIs for voice, SMS, video, and verification used by developers worldwide.',
    website: 'https://www.vonage.com',
    docs: 'https://developer.vonage.com',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 78,
    features: ['Voice API', 'SMS', 'Video', 'Verify'],
    tags: ['Telephony', 'SMS', 'Video'],
    alternatives: ['twilio', 'plivo'],
  },
  {
    categoryId: 'voice',
    name: 'Speechmatics',
    shortDescription: 'Accurate speech-to-text in 50+ languages.',
    longDescription:
      'Speechmatics delivers industry-leading transcription accuracy across 50+ languages with realtime streaming.',
    website: 'https://www.speechmatics.com',
    docs: 'https://docs.speechmatics.com',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 74,
    features: ['Speech-to-text', '50+ languages', 'Realtime streaming', 'Diarization'],
    tags: ['STT', 'Multilingual', 'Realtime'],
    alternatives: ['assemblyai', 'deepgram'],
  },
  {
    categoryId: 'translation',
    name: 'Google Cloud Translation',
    shortDescription: 'Neural machine translation with 100+ languages.',
    longDescription:
      'Google Cloud Translation uses neural models to translate text and websites across 100+ languages at scale.',
    website: 'https://cloud.google.com/translate',
    docs: 'https://cloud.google.com/translate/docs',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 92,
    featured: true,
    features: ['Neural translation', '100+ languages', 'Document translation', 'Glossary'],
    tags: ['Translation', 'Google', 'Neural'],
    alternatives: ['deepl', 'azure-translator'],
  },
  {
    categoryId: 'translation',
    name: 'DeepL',
    shortDescription: 'High-quality translation API with natural results.',
    longDescription:
      'DeepL is known for producing the most natural-sounding translations with a developer API and document support.',
    website: 'https://www.deepl.com',
    docs: 'https://developers.deepl.com',
    github: 'DeepLcom/deepl-node',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 88,
    features: ['High quality', 'Document translation', 'Glossary', 'API'],
    tags: ['Translation', 'High quality', 'API'],
    alternatives: ['google-translate', 'azure-translator'],
  },
  {
    categoryId: 'translation',
    name: 'Amazon Translate',
    shortDescription: 'Fast, cost-effective neural translation from AWS.',
    longDescription:
      'Amazon Translate offers high-quality neural machine translation tightly integrated with the AWS ecosystem.',
    website: 'https://aws.amazon.com/translate',
    docs: 'https://docs.aws.amazon.com/translate',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 80,
    features: ['Neural translation', 'Realtime', 'Batch jobs', 'Custom terminology'],
    tags: ['Translation', 'AWS', 'Neural'],
    alternatives: ['google-translate', 'deepl'],
  },
  {
    categoryId: 'translation',
    name: 'Azure Translator',
    shortDescription: 'Microsoft\u2019s translation API for text and documents.',
    longDescription:
      'Azure Translator provides text, document, and custom translation services with broad language coverage.',
    website: 'https://azure.microsoft.com/products/ai-services/translator',
    docs: 'https://learn.microsoft.com/azure/ai-services/translator',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 82,
    features: ['Text translation', 'Document translation', 'Custom translator', 'Speech translation'],
    tags: ['Translation', 'Azure', 'Custom'],
    alternatives: ['google-translate', 'deepl'],
  },
  {
    categoryId: 'translation',
    name: 'LibreTranslate',
    shortDescription: 'Open-source, self-hostable translation API.',
    longDescription:
      'LibreTranslate is a free and open-source machine translation API you can self-host for privacy-sensitive apps.',
    website: 'https://libretranslate.com',
    docs: 'https://libretranslate.com/docs',
    github: 'LibreTranslate/LibreTranslate',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 76,
    features: ['Self-hosted', 'Open source', 'REST API', 'Privacy'],
    tags: ['Translation', 'Open source', 'Self-hosted'],
    alternatives: ['argos-translate', 'google-translate'],
  },
  {
    categoryId: 'translation',
    name: 'Argos Translate',
    shortDescription: 'Offline neural translation that runs entirely locally.',
    longDescription:
      'Argos Translate provides offline, open-source neural machine translation for fully local deployments.',
    website: 'https://www.argosopentech.com',
    docs: 'https://github.com/argosopentech/argos-translate',
    github: 'argosopentech/argos-translate',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 68,
    features: ['Offline translation', 'Open source', 'Local models', 'CLI and API'],
    tags: ['Translation', 'Offline', 'Open source'],
    alternatives: ['libretranslate', 'google-translate'],
  },
  {
    categoryId: 'ocr',
    name: 'Tesseract OCR',
    shortDescription: 'Open-source OCR engine with 100+ language support.',
    longDescription:
      'Tesseract is the most widely used open-source OCR engine, supporting over 100 languages and active community development.',
    website: 'https://github.com/tesseract-ocr/tesseract',
    docs: 'https://tesseract-ocr.github.io',
    github: 'tesseract-ocr/tesseract',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 90,
    featured: true,
    features: ['Open source', '100+ languages', 'Layout analysis', 'Self-hosted'],
    tags: ['OCR', 'Open source', 'Self-hosted'],
    alternatives: ['google-vision', 'azure-vision'],
  },
  {
    categoryId: 'ocr',
    name: 'Google Cloud Vision',
    shortDescription: 'Cloud OCR with document AI and high accuracy.',
    longDescription:
      'Google Cloud Vision offers OCR and document AI with high accuracy, handwriting support, and a managed API.',
    website: 'https://cloud.google.com/vision',
    docs: 'https://cloud.google.com/vision/docs',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 88,
    features: ['Cloud OCR', 'Handwriting', 'Document AI', 'Text detection'],
    tags: ['OCR', 'Google', 'Managed'],
    alternatives: ['textract', 'azure-vision'],
  },
  {
    categoryId: 'ocr',
    name: 'Amazon Textract',
    shortDescription: 'Extract text and data from documents and forms.',
    longDescription:
      'Amazon Textract goes beyond OCR to extract data from forms, tables, and PDFs using machine learning.',
    website: 'https://aws.amazon.com/textract',
    docs: 'https://docs.aws.amazon.com/textract',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 84,
    features: ['Forms and tables', 'Document extraction', 'Queries', 'AWS integration'],
    tags: ['OCR', 'Documents', 'AWS'],
    alternatives: ['google-vision', 'azure-vision'],
  },
  {
    categoryId: 'ocr',
    name: 'Azure AI Vision',
    shortDescription: 'Microsoft\u2019s OCR and image analysis API.',
    longDescription:
      'Azure AI Vision provides OCR, image analysis, and layout recognition with Microsoft\u2019s managed AI services.',
    website: 'https://azure.microsoft.com/products/ai-services/ai-vision',
    docs: 'https://learn.microsoft.com/azure/ai-services/computer-vision',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 82,
    features: ['OCR', 'Layout recognition', 'Image analysis', 'Read API'],
    tags: ['OCR', 'Azure', 'Managed'],
    alternatives: ['textract', 'google-vision'],
  },
  {
    categoryId: 'ocr',
    name: 'PaddleOCR',
    shortDescription: 'Open-source OCR toolkit with 80+ languages.',
    longDescription:
      'PaddleOCR is a practical OCR toolkit from Baidu supporting 80+ languages, including excellent Chinese support.',
    website: 'https://www.paddlepaddle.org.cn',
    docs: 'https://paddlepaddle.github.io/PaddleOCR',
    github: 'PaddlePaddle/PaddleOCR',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 80,
    features: ['80+ languages', 'Text detection', 'Text recognition', 'Open source'],
    tags: ['OCR', 'Open source', 'Chinese'],
    alternatives: ['tesseract', 'google-vision'],
  },
  {
    categoryId: 'ocr',
    name: 'OCR.space',
    shortDescription: 'Simple OCR API with free tier and batch processing.',
    longDescription:
      'OCR.space offers an easy-to-use OCR API supporting 25+ languages with a generous free tier.',
    website: 'https://ocr.space',
    docs: 'https://ocr.space/ocrapi',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 74,
    features: ['OCR API', '25+ languages', 'Free tier', 'Batch processing'],
    tags: ['OCR', 'API', 'Free tier'],
    alternatives: ['google-vision', 'tesseract'],
  },
  {
    categoryId: 'ocr',
    name: 'Nanonets',
    shortDescription: 'Document AI with intelligent document processing.',
    longDescription:
      'Nanonets automates document workflows with AI OCR, document classification, and data extraction.',
    website: 'https://nanonets.com',
    docs: 'https://docs.nanonets.com',
    pricingModel: 'subscription',
    freeTier: false,
    openSource: false,
    popularityScore: 72,
    features: ['Document AI', 'Data extraction', 'Workflow automation', 'Classification'],
    tags: ['OCR', 'Document AI', 'Automation'],
    alternatives: ['textract', 'azure-vision'],
  },
];

export const aiProviders = buildProviders(rows);
