import { buildProviders, type SeedProvider } from './helpers';

const rows: SeedProvider[] = [
  {
    categoryId: 'frontend',
    name: 'React',
    shortDescription: 'The industry-standard library for building component-based user interfaces.',
    longDescription:
      'React is a declarative JavaScript library for building component-based user interfaces. With a massive ecosystem, excellent tooling, and broad hiring pool, it is the default choice for most web frontends.',
    website: 'https://react.dev',
    docs: 'https://react.dev',
    github: 'facebook/react',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 98,
    featured: true,
    features: ['Component-based UI', 'Hooks and state management', 'Huge ecosystem', 'Server components'],
    tags: ['UI', 'JavaScript', 'Component library'],
    alternatives: ['vue', 'svelte'],
  },
  {
    categoryId: 'frontend',
    name: 'Next.js',
    shortDescription: 'The React framework for production with SSR, SSG, and edge rendering.',
    longDescription:
      'Next.js is the most popular React framework, providing file-based routing, server-side rendering, static generation, image optimization, and API routes out of the box.',
    website: 'https://nextjs.org',
    docs: 'https://nextjs.org/docs',
    github: 'vercel/next.js',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 97,
    featured: true,
    features: ['Server-side rendering', 'Static site generation', 'API routes', 'Image optimization'],
    tags: ['React', 'SSR', 'Framework'],
    alternatives: ['astro', 'remix'],
  },
  {
    categoryId: 'frontend',
    name: 'Vue',
    shortDescription: 'Progressive JavaScript framework with a gentle learning curve.',
    longDescription:
      'Vue is a progressive framework for building user interfaces. Its single-file components, reactive data system, and approachable syntax make it a favorite for developers of all levels.',
    website: 'https://vuejs.org',
    docs: 'https://vuejs.org/guide',
    github: 'vuejs/core',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 92,
    features: ['Single-file components', 'Reactivity', 'Composition API', 'Progressive adoption'],
    tags: ['UI', 'JavaScript', 'Framework'],
    alternatives: ['react', 'svelte'],
  },
  {
    categoryId: 'frontend',
    name: 'Svelte',
    shortDescription: 'Compiler-driven UI framework with tiny bundles and no virtual DOM.',
    longDescription:
      'Svelte shifts work from the browser to the compiler, producing small, fast bundles with truly reactive state and no virtual DOM overhead.',
    website: 'https://svelte.dev',
    docs: 'https://svelte.dev/docs',
    github: 'sveltejs/svelte',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 88,
    features: ['Compiler-based', 'Small bundle size', 'True reactivity', 'Transitions built in'],
    tags: ['UI', 'Compiler', 'Framework'],
    alternatives: ['react', 'vue'],
  },
  {
    categoryId: 'frontend',
    name: 'Angular',
    shortDescription: 'Full-featured TypeScript framework for large-scale enterprise apps.',
    longDescription:
      'Angular is a batteries-included TypeScript framework with dependency injection, routing, forms, and testing tools, ideal for large teams and enterprise applications.',
    website: 'https://angular.dev',
    docs: 'https://angular.dev',
    github: 'angular/angular',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 90,
    features: ['TypeScript by default', 'Dependency injection', 'Built-in forms', 'Testing tools'],
    tags: ['TypeScript', 'Enterprise', 'Framework'],
    alternatives: ['react', 'vue'],
  },
  {
    categoryId: 'frontend',
    name: 'Astro',
    shortDescription: 'Content-focused framework that ships zero JavaScript by default.',
    longDescription:
      'Astro builds content-rich websites with an islands architecture, shipping zero JavaScript by default and supporting multiple UI frameworks.',
    website: 'https://astro.build',
    docs: 'https://docs.astro.build',
    github: 'withastro/astro',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 86,
    features: ['Islands architecture', 'Zero JS by default', 'Content collections', 'Multi-framework'],
    tags: ['Content', 'Static', 'Framework'],
    alternatives: ['nextjs', 'remix'],
  },
  {
    categoryId: 'frontend',
    name: 'Remix',
    shortDescription: 'Full-stack React framework focused on web fundamentals and performance.',
    longDescription:
      'Remix is a full-stack React framework that embraces web standards — nested routing, progressive enhancement, and edge rendering.',
    website: 'https://remix.run',
    docs: 'https://remix.run/docs',
    github: 'remix-run/remix',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 80,
    features: ['Nested routes', 'Progressive enhancement', 'Edge rendering', 'Loaders and actions'],
    tags: ['React', 'Full-stack', 'Framework'],
    alternatives: ['nextjs', 'astro'],
  },
  {
    categoryId: 'backend',
    name: 'Node.js',
    shortDescription: 'JavaScript runtime built on V8 for fast, scalable server-side apps.',
    longDescription:
      'Node.js is an asynchronous, event-driven JavaScript runtime that powers millions of server-side applications and tools.',
    website: 'https://nodejs.org',
    docs: 'https://nodejs.org/docs',
    github: 'nodejs/node',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 96,
    featured: true,
    features: ['Async runtime', 'npm ecosystem', 'Streams', 'Serverless ready'],
    tags: ['JavaScript', 'Runtime', 'Server'],
    alternatives: ['deno'],
  },
  {
    categoryId: 'backend',
    name: 'Express',
    shortDescription: 'Minimal and flexible Node.js web application framework.',
    longDescription:
      'Express is the de facto standard Node.js web framework, providing a thin layer of routing and middleware on top of Node HTTP servers.',
    website: 'https://expressjs.com',
    docs: 'https://expressjs.com',
    github: 'expressjs/express',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 91,
    features: ['Routing', 'Middleware', 'Minimal core', 'Huge ecosystem'],
    tags: ['Node.js', 'Web framework', 'API'],
    alternatives: ['nestjs', 'fastify'],
  },
  {
    categoryId: 'backend',
    name: 'NestJS',
    shortDescription: 'Progressive, opinionated Node.js framework with TypeScript first.',
    longDescription:
      'NestJS provides an enterprise-grade architecture for Node.js with dependency injection, modularity, and decorators, built on top of Express or Fastify.',
    website: 'https://nestjs.com',
    docs: 'https://docs.nestjs.com',
    github: 'nestjs/nest',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 87,
    features: ['Dependency injection', 'Modular architecture', 'TypeScript first', 'Testing utilities'],
    tags: ['TypeScript', 'Node.js', 'Framework'],
    alternatives: ['express', 'spring-boot'],
  },
  {
    categoryId: 'backend',
    name: 'FastAPI',
    shortDescription: 'Modern, high-performance Python web framework with automatic docs.',
    longDescription:
      'FastAPI builds Python APIs at speed with automatic OpenAPI documentation, data validation, and async support.',
    website: 'https://fastapi.tiangolo.com',
    docs: 'https://fastapi.tiangolo.com',
    github: 'fastapi/fastapi',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 89,
    features: ['Automatic docs', 'Pydantic validation', 'Async support', 'OpenAPI'],
    tags: ['Python', 'API', 'Framework'],
    alternatives: ['django', 'express'],
  },
  {
    categoryId: 'backend',
    name: 'Django',
    shortDescription: 'Batteries-included Python web framework with admin and ORM.',
    longDescription:
      'Django is a high-level Python framework that includes an ORM, admin interface, authentication, and templating out of the box.',
    website: 'https://www.djangoproject.com',
    docs: 'https://docs.djangoproject.com',
    github: 'django/django',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 85,
    features: ['ORM', 'Admin interface', 'Authentication', 'Templating'],
    tags: ['Python', 'Web framework', 'Batteries-included'],
    alternatives: ['fastapi', 'rails'],
  },
  {
    categoryId: 'backend',
    name: 'Spring Boot',
    shortDescription: 'Production-grade Java framework with embedded servers and auto-config.',
    longDescription:
      'Spring Boot simplifies building production-ready Java applications with embedded web servers, auto-configuration, and a vast ecosystem.',
    website: 'https://spring.io/projects/spring-boot',
    docs: 'https://docs.spring.io/spring-boot',
    github: 'spring-projects/spring-boot',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 88,
    features: ['Auto-configuration', 'Embedded server', 'Microservices', 'Security'],
    tags: ['Java', 'Microservices', 'Framework'],
    alternatives: ['nestjs', 'express'],
  },
  {
    categoryId: 'backend',
    name: 'Ruby on Rails',
    shortDescription: 'Developer-convention web framework with rapid prototyping.',
    longDescription:
      'Ruby on Rails prioritizes convention over configuration, letting teams ship full-stack apps quickly with an elegant ORM and scaffolding.',
    website: 'https://rubyonrails.org',
    docs: 'https://guides.rubyonrails.org',
    github: 'rails/rails',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 78,
    features: ['Convention over configuration', 'ActiveRecord ORM', 'Scaffolding', 'MVC'],
    tags: ['Ruby', 'Web framework', 'Full-stack'],
    alternatives: ['django', 'express'],
  },
  {
    categoryId: 'authentication',
    name: 'Clerk',
    shortDescription: 'Drop-in auth components and pre-built UI for React, Next.js, and more.',
    longDescription:
      'Clerk provides hosted authentication with pre-built UI components, social login, MFA, and user management that integrates in minutes.',
    website: 'https://clerk.com',
    docs: 'https://clerk.com/docs',
    github: 'clerk/javascript',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 90,
    featured: true,
    features: ['Pre-built UI', 'Social login', 'Organization management', 'MFA'],
    tags: ['OAuth', 'Pre-built UI', 'Session management'],
    alternatives: ['auth0', 'supabase-auth'],
  },
  {
    categoryId: 'authentication',
    name: 'Auth0',
    shortDescription: 'Enterprise-grade identity platform with SSO, MFA, and social login.',
    longDescription:
      'Auth0 is a flexible, drop-in authentication and authorization platform used by enterprises for SSO, MFA, and passwordless flows.',
    website: 'https://auth0.com',
    docs: 'https://auth0.com/docs',
    github: 'auth0/auth0-node',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 88,
    features: ['SSO', 'MFA', 'Passwordless', 'Enterprise connections'],
    tags: ['OAuth', 'SSO', 'MFA'],
    alternatives: ['clerk', 'workos'],
  },
  {
    categoryId: 'authentication',
    name: 'Supabase Auth',
    shortDescription: 'Open-source auth with row-level security, built on PostgreSQL.',
    longDescription:
      'Supabase Auth is an open-source authentication system with email, OAuth, and phone login, tightly integrated with Postgres row-level security.',
    website: 'https://supabase.com/docs/guides/auth',
    docs: 'https://supabase.com/docs/guides/auth',
    github: 'supabase/auth',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 85,
    features: ['Row-level security', 'Email and OAuth', 'Magic links', 'Realtime'],
    tags: ['Open Source', 'OAuth', 'RLS'],
    alternatives: ['nextauth', 'firebase-auth'],
  },
  {
    categoryId: 'authentication',
    name: 'NextAuth.js',
    shortDescription: 'Flexible auth library for Next.js with 70+ built-in providers.',
    longDescription:
      'NextAuth.js (now Auth.js) is an open-source authentication library that works with any Next.js app and supports dozens of OAuth providers.',
    website: 'https://next-auth.js.org',
    docs: 'https://next-auth.js.org/getting-started/introduction',
    github: 'nextauthjs/next-auth',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 92,
    featured: true,
    features: ['70+ providers', 'JWT sessions', 'Database adapters', 'Middleware'],
    tags: ['Open Source', 'OAuth', 'JWT'],
    alternatives: ['clerk', 'lucia'],
  },
  {
    categoryId: 'authentication',
    name: 'Firebase Auth',
    shortDescription: 'Google-backed authentication with phone, email, and social login.',
    longDescription:
      'Firebase Authentication provides simple SDKs for email, password, phone, and social login, backed by Google infrastructure.',
    website: 'https://firebase.google.com/products/auth',
    docs: 'https://firebase.google.com/docs/auth',
    github: 'firebase/firebase-js-sdk',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 87,
    features: ['Phone auth', 'Email and password', 'Social login', 'Anonymous auth'],
    tags: ['OAuth', 'Phone auth', 'Google'],
    alternatives: ['supabase-auth', 'auth0'],
  },
  {
    categoryId: 'authentication',
    name: 'Lucia',
    shortDescription: 'Lightweight, type-safe auth library with full control over sessions.',
    longDescription:
      'Lucia is a minimalist, type-safe authentication library that gives you full control over session storage and login flows.',
    website: 'https://lucia-auth.com',
    docs: 'https://lucia-auth.com',
    github: 'lucia-auth/lucia',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 70,
    features: ['Sessions', 'Database adapters', 'Type-safe', 'Framework agnostic'],
    tags: ['Open Source', 'Sessions', 'TypeScript'],
    alternatives: ['nextauth', 'clerk'],
  },
  {
    categoryId: 'authentication',
    name: 'WorkOS',
    shortDescription: 'Enterprise auth with SSO, directory sync, and admin portal.',
    longDescription:
      'WorkOS offers enterprise-ready authentication with SAML/OIDC SSO, directory sync, and an admin portal, perfect for B2B SaaS.',
    website: 'https://workos.com',
    docs: 'https://workos.com/docs',
    github: 'workos/workos-node',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 72,
    features: ['SSO', 'Directory sync', 'Admin portal', 'Audit logs'],
    tags: ['Enterprise', 'SSO', 'B2B'],
    alternatives: ['auth0', 'clerk'],
  },
  {
    categoryId: 'database',
    name: 'PostgreSQL',
    shortDescription: 'Powerful open-source relational database with JSON support and extensions.',
    longDescription:
      'PostgreSQL is the most advanced open-source relational database, offering ACID transactions, JSON support, and a rich extension ecosystem.',
    website: 'https://www.postgresql.org',
    docs: 'https://www.postgresql.org/docs',
    github: 'postgres/postgres',
    pricingModel: 'open-source',
    freeTier: true,
    openSource: true,
    popularityScore: 97,
    featured: true,
    features: ['ACID transactions', 'JSON/JSONB', 'Full-text search', 'Extensions'],
    tags: ['SQL', 'Relational', 'ACID'],
    alternatives: ['cockroachdb', 'neon'],
  },
  {
    categoryId: 'database',
    name: 'MongoDB',
    shortDescription: 'Document-based NoSQL database built for developers and scaling.',
    longDescription:
      'MongoDB is the leading document database, storing flexible JSON-like documents with horizontal scaling and a rich aggregation pipeline.',
    website: 'https://www.mongodb.com',
    docs: 'https://www.mongodb.com/docs',
    github: 'mongodb/mongo',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 93,
    features: ['Document model', 'Aggregation pipeline', 'Replica sets', 'Change streams'],
    tags: ['NoSQL', 'Document', 'Scalable'],
    alternatives: ['firebase-db', 'postgresql'],
  },
  {
    categoryId: 'database',
    name: 'Supabase',
    shortDescription: 'Postgres database with realtime, auth, and storage in one platform.',
    longDescription:
      'Supabase is an open-source Firebase alternative offering a hosted Postgres database with realtime subscriptions, auth, and storage.',
    website: 'https://supabase.com',
    docs: 'https://supabase.com/docs',
    github: 'supabase/supabase',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 91,
    features: ['Realtime', 'Row-level security', 'PostgREST API', 'Edge functions'],
    tags: ['SQL', 'Postgres', 'Realtime'],
    alternatives: ['neon', 'firebase-db'],
  },
  {
    categoryId: 'database',
    name: 'Neon',
    shortDescription: 'Serverless Postgres with branching, instant scaling, and copy-on-write.',
    longDescription:
      'Neon separates storage and compute to deliver serverless Postgres with database branching, instant scaling, and autoscaling to zero.',
    website: 'https://neon.tech',
    docs: 'https://neon.tech/docs',
    github: 'neondatabase/neon',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 85,
    features: ['Branching', 'Autoscaling', 'Serverless', 'PITR'],
    tags: ['SQL', 'Serverless', 'Postgres'],
    alternatives: ['supabase', 'planetscale'],
  },
  {
    categoryId: 'database',
    name: 'PlanetScale',
    shortDescription: 'MySQL-compatible serverless database with Git-like branching.',
    longDescription:
      'PlanetScale is a MySQL-compatible serverless database with branch-based development workflows and automatic scaling.',
    website: 'https://planetscale.com',
    docs: 'https://planetscale.com/docs',
    pricingModel: 'subscription',
    freeTier: false,
    openSource: false,
    popularityScore: 82,
    features: ['Git-like branching', 'MySQL compatible', 'Automatic scaling', 'Deploy requests'],
    tags: ['SQL', 'Serverless', 'MySQL'],
    alternatives: ['neon', 'turso'],
  },
  {
    categoryId: 'database',
    name: 'Firestore',
    shortDescription: 'NoSQL document database with realtime sync and offline support.',
    longDescription:
      'Cloud Firestore is a flexible, scalable NoSQL database for mobile and web apps with realtime listeners and offline persistence.',
    website: 'https://firebase.google.com/products/firestore',
    docs: 'https://firebase.google.com/docs/firestore',
    github: 'firebase/firebase-js-sdk',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 84,
    features: ['Realtime sync', 'Offline support', 'Security rules', 'Multi-region'],
    tags: ['NoSQL', 'Realtime', 'Serverless'],
    alternatives: ['mongodb', 'supabase'],
  },
  {
    categoryId: 'database',
    name: 'CockroachDB',
    shortDescription: 'Distributed, cloud-native SQL database built for resilience.',
    longDescription:
      'CockroachDB is a distributed SQL database that scales horizontally while remaining PostgreSQL-compatible, designed for high availability.',
    website: 'https://www.cockroachlabs.com',
    docs: 'https://www.cockroachlabs.com/docs',
    github: 'cockroachdb/cockroach',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 76,
    features: ['Horizontal scaling', 'Postgres compatible', 'Survivability', 'Multi-region'],
    tags: ['SQL', 'Distributed', 'Cloud-native'],
    alternatives: ['postgresql', 'neon'],
  },
  {
    categoryId: 'database',
    name: 'Turso',
    shortDescription: 'Edge-native SQLite database for globally distributed reads.',
    longDescription:
      'Turso distributes SQLite databases to the edge with LibSQL, enabling low-latency reads close to users.',
    website: 'https://turso.tech',
    docs: 'https://docs.turso.tech',
    github: 'tursodatabase/libsql',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 74,
    features: ['Edge distribution', 'SQLite compatible', 'Multi-tenant', 'Branching'],
    tags: ['SQLite', 'Edge', 'Serverless'],
    alternatives: ['planetscale', 'neon'],
  },
  {
    categoryId: 'hosting',
    name: 'Vercel',
    shortDescription: 'Frontend cloud built for Next.js with edge functions and previews.',
    longDescription:
      'Vercel deploys frontend applications globally with instant previews, edge functions, and first-class Next.js support.',
    website: 'https://vercel.com',
    docs: 'https://vercel.com/docs',
    github: 'vercel/vercel',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 95,
    featured: true,
    features: ['Preview deployments', 'Edge functions', 'Analytics', 'Serverless'],
    tags: ['Next.js', 'Edge', 'Serverless'],
    alternatives: ['netlify', 'cloudflare-pages'],
  },
  {
    categoryId: 'hosting',
    name: 'Netlify',
    shortDescription: 'All-in-one platform for deploying static and serverless sites.',
    longDescription:
      'Netlify deploys static sites and serverless functions with a powerful edge network, forms, and split testing.',
    website: 'https://www.netlify.com',
    docs: 'https://docs.netlify.com',
    github: 'netlify/netlify',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 90,
    features: ['Static deploys', 'Netlify Functions', 'Forms', 'Split testing'],
    tags: ['Static', 'Serverless', 'CI/CD'],
    alternatives: ['vercel', 'cloudflare-pages'],
  },
  {
    categoryId: 'hosting',
    name: 'Railway',
    shortDescription: 'Deploy apps and databases with zero config and instant provisioning.',
    longDescription:
      'Railway provides instant deployment for full-stack apps and databases with a simple, flexible pricing model.',
    website: 'https://railway.app',
    docs: 'https://docs.railway.app',
    github: 'railwayapp/railway',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 84,
    features: ['Zero config', 'Databases', 'Volumes', 'Monitoring'],
    tags: ['Full-stack', 'Zero config', 'DB hosting'],
    alternatives: ['render', 'fly'],
  },
  {
    categoryId: 'hosting',
    name: 'Fly.io',
    shortDescription: 'Run full-stack apps and databases close to users globally.',
    longDescription:
      'Fly.io runs full-stack apps on dedicated VMs distributed across regions, with built-in Anycast networking and database support.',
    website: 'https://fly.io',
    docs: 'https://fly.io/docs',
    github: 'superfly/flyctl',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 82,
    features: ['Global regions', 'Fly Machines', 'Anycast', 'Docker support'],
    tags: ['Full-stack', 'Global', 'Docker'],
    alternatives: ['railway', 'render'],
  },
  {
    categoryId: 'hosting',
    name: 'Render',
    shortDescription: 'Unified cloud for web services, background workers, and databases.',
    longDescription:
      'Render offers managed web services, background workers, cron jobs, and databases with simple deploy-from-Git workflows.',
    website: 'https://render.com',
    docs: 'https://render.com/docs',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 83,
    features: ['Web services', 'Background workers', 'Databases', 'Auto deploys'],
    tags: ['Full-stack', 'Docker', 'DB hosting'],
    alternatives: ['railway', 'fly'],
  },
  {
    categoryId: 'hosting',
    name: 'Cloudflare Pages',
    shortDescription: 'Fast, global static and functions hosting with preview deployments.',
    longDescription:
      'Cloudflare Pages hosts static sites and serverless functions on Cloudflare\u2019s global edge network with instant previews.',
    website: 'https://pages.cloudflare.com',
    docs: 'https://developers.cloudflare.com/pages',
    github: 'cloudflare/workers-sdk',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 85,
    features: ['Global edge', 'Functions', 'Preview deploys', 'Large bandwidth'],
    tags: ['Static', 'Edge', 'Functions'],
    alternatives: ['netlify', 'vercel'],
  },
  {
    categoryId: 'cloud',
    name: 'Amazon Web Services',
    shortDescription: 'The largest cloud platform with compute, storage, and 200+ services.',
    longDescription:
      'AWS is the most mature cloud provider, offering a vast catalog of compute, storage, database, and machine learning services.',
    website: 'https://aws.amazon.com',
    docs: 'https://docs.aws.amazon.com',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 98,
    featured: true,
    features: ['Compute', 'Managed databases', 'Object storage', 'Serverless'],
    tags: ['IaaS', 'Compute', 'Managed services'],
    alternatives: ['google-cloud', 'azure'],
  },
  {
    categoryId: 'cloud',
    name: 'Google Cloud',
    shortDescription: 'Google\u2019s cloud platform with best-in-class data and AI services.',
    longDescription:
      'Google Cloud Platform offers robust compute, data analytics, and machine learning services including BigQuery and Vertex AI.',
    website: 'https://cloud.google.com',
    docs: 'https://cloud.google.com/docs',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 94,
    features: ['BigQuery', 'Kubernetes Engine', 'Vertex AI', 'Cloud Run'],
    tags: ['IaaS', 'Data', 'AI'],
    alternatives: ['aws', 'azure'],
  },
  {
    categoryId: 'cloud',
    name: 'Microsoft Azure',
    shortDescription: 'Enterprise cloud with deep Windows and Microsoft 365 integration.',
    longDescription:
      'Microsoft Azure is a leading enterprise cloud with strong Windows, Active Directory, and developer tooling integration.',
    website: 'https://azure.microsoft.com',
    docs: 'https://learn.microsoft.com/azure',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 95,
    features: ['Virtual machines', 'App services', 'Azure DevOps', 'AI services'],
    tags: ['IaaS', 'Enterprise', 'Hybrid cloud'],
    alternatives: ['aws', 'google-cloud'],
  },
  {
    categoryId: 'cloud',
    name: 'DigitalOcean',
    shortDescription: 'Simple, developer-friendly cloud with predictable pricing.',
    longDescription:
      'DigitalOcean offers easy-to-use droplets, managed databases, and Kubernetes with predictable flat pricing.',
    website: 'https://www.digitalocean.com',
    docs: 'https://docs.digitalocean.com',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 88,
    features: ['Droplets', 'Managed databases', 'Managed Kubernetes', 'App platform'],
    tags: ['VPS', 'Simple', 'Predictable pricing'],
    alternatives: ['hetzner', 'linode'],
  },
  {
    categoryId: 'cloud',
    name: 'Hetzner',
    shortDescription: 'High-performance, low-cost European cloud and dedicated servers.',
    longDescription:
      'Hetzner provides powerful dedicated servers and cloud instances at some of the lowest prices, popular in Europe.',
    website: 'https://www.hetzner.com',
    docs: 'https://docs.hetzner.com',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 84,
    features: ['Dedicated servers', 'Cloud instances', 'Storage boxes', 'Volumes'],
    tags: ['VPS', 'Bare metal', 'Affordable'],
    alternatives: ['digitalocean', 'linode'],
  },
  {
    categoryId: 'cloud',
    name: 'Akamai Linode',
    shortDescription: 'Developer-friendly cloud computing with simple, predictable pricing.',
    longDescription:
      'Linode (now part of Akamai) offers straightforward Linux cloud computing with fast VPS instances and managed services.',
    website: 'https://www.linode.com',
    docs: 'https://www.linode.com/docs',
    pricingModel: 'usage-based',
    freeTier: false,
    openSource: false,
    popularityScore: 78,
    features: ['VPS instances', 'Block storage', 'Managed Kubernetes', 'Object storage'],
    tags: ['VPS', 'Simple', 'Affordable'],
    alternatives: ['digitalocean', 'hetzner'],
  },
  {
    categoryId: 'storage',
    name: 'Cloudinary',
    shortDescription: 'Media management with on-the-fly image and video transformations.',
    longDescription:
      'Cloudinary manages images and videos end to end, with on-the-fly transformations, CDN delivery, and generative AI features.',
    website: 'https://cloudinary.com',
    docs: 'https://cloudinary.com/documentation',
    github: 'cloudinary/cloudinary_npm',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 90,
    featured: true,
    features: ['Image transformations', 'Video processing', 'CDN delivery', 'Generative AI'],
    tags: ['Images', 'Video', 'CDN'],
    alternatives: ['cloudflare-r2', 'bunny'],
  },
  {
    categoryId: 'storage',
    name: 'AWS S3',
    shortDescription: 'Industry-standard object storage with unmatched scale and durability.',
    longDescription:
      'Amazon S3 is the de facto standard for object storage, offering industry-leading durability, scale, and ecosystem integration.',
    website: 'https://aws.amazon.com/s3',
    docs: 'https://docs.aws.amazon.com/s3',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 96,
    features: ['Object storage', 'Lifecycle rules', 'Versioning', 'Glacier archive'],
    tags: ['Object storage', 'Scalable', 'AWS'],
    alternatives: ['cloudflare-r2', 'backblaze'],
  },
  {
    categoryId: 'storage',
    name: 'Supabase Storage',
    shortDescription: 'S3-compatible storage with image resizing and RLS policies.',
    longDescription:
      'Supabase Storage provides S3-compatible object storage tightly integrated with Postgres row-level security and image resizing.',
    website: 'https://supabase.com/docs/guides/storage',
    docs: 'https://supabase.com/docs/guides/storage',
    github: 'supabase/supabase',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: true,
    popularityScore: 85,
    features: ['S3 compatible', 'RLS policies', 'Image resizing', 'CDN'],
    tags: ['S3-compatible', 'RLS', 'Images'],
    alternatives: ['s3', 'uploadthing'],
  },
  {
    categoryId: 'storage',
    name: 'UploadThing',
    shortDescription: 'Type-safe file uploads for Next.js with zero infrastructure.',
    longDescription:
      'UploadThing provides type-safe, end-to-end file uploads for Next.js with built-in auth handling and image optimization.',
    website: 'https://uploadthing.com',
    docs: 'https://docs.uploadthing.com',
    github: 'pingdotgg/uploadthing',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 78,
    features: ['Type-safe uploads', 'Next.js integration', 'Presigned URLs', 'Image optimization'],
    tags: ['File upload', 'TypeScript', 'Next.js'],
    alternatives: ['cloudinary', 'supabase-storage'],
  },
  {
    categoryId: 'storage',
    name: 'Backblaze B2',
    shortDescription: 'Affordable S3-compatible cloud storage at a fraction of the cost.',
    longDescription:
      'Backblaze B2 is low-cost, S3-compatible object storage with generous free egress to major cloud providers.',
    website: 'https://www.backblaze.com/cloud-storage',
    docs: 'https://www.backblaze.com/docs/cloud-storage',
    github: 'Backblaze/B2_Command_Line_Tool',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 80,
    features: ['S3 compatible', 'Low cost', 'Free egress to clouds', 'Large files'],
    tags: ['S3-compatible', 'Affordable'],
    alternatives: ['s3', 'cloudflare-r2'],
  },
  {
    categoryId: 'storage',
    name: 'Cloudflare R2',
    shortDescription: 'Zero-egress-fee S3-compatible object storage on the edge.',
    longDescription:
      'Cloudflare R2 offers S3-compatible object storage with no egress fees and global edge access.',
    website: 'https://developers.cloudflare.com/r2',
    docs: 'https://developers.cloudflare.com/r2',
    pricingModel: 'usage-based',
    freeTier: true,
    openSource: false,
    popularityScore: 88,
    features: ['Zero egress fees', 'S3 compatible', 'Global edge', 'R2 dev bindings'],
    tags: ['S3-compatible', 'Edge', 'No egress fees'],
    alternatives: ['s3', 'backblaze'],
  },
  {
    categoryId: 'storage',
    name: 'Firebase Storage',
    shortDescription: 'Google-backed object storage built for mobile and web apps.',
    longDescription:
      'Firebase Storage provides secure object uploads and downloads backed by Google Cloud Storage with simple client SDKs.',
    website: 'https://firebase.google.com/products/storage',
    docs: 'https://firebase.google.com/docs/storage',
    github: 'firebase/firebase-js-sdk',
    pricingModel: 'freemium',
    freeTier: true,
    openSource: false,
    popularityScore: 83,
    features: ['Client SDKs', 'Security rules', 'Google Cloud Storage', 'Large transfers'],
    tags: ['File storage', 'Firebase', 'Google Cloud'],
    alternatives: ['supabase-storage', 's3'],
  },
];

export const coreProviders = buildProviders(rows);
