import {
  ShieldCheck,
  Database,
  HardDrive,
  Video,
  Globe,
  Mail,
  Bell,
  BarChart3,
  Cloud,
  Layers,
  MonitorSmartphone,
  Server,
  CloudCog,
  CreditCard,
  Brain,
  Sparkles,
  Search,
  Zap,
  Activity,
  ScrollText,
  LayoutDashboard,
  Rocket,
  Map,
  ScanText,
  Languages,
  Mic,
  MessageSquare,
  FlaskConical,
  Workflow,
  Box,
  CloudLightning,
  Repeat,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type Category = {
  id: string;
  name: string;
  icon: LucideIcon;
  providers: number;
  description: string;
  gradient: string;
  iconColor: string;
  recommended: string;
};

export const categories: Category[] = [
  {
    id: 'frontend',
    name: 'Frontend',
    icon: MonitorSmartphone,
    providers: 7,
    description: 'Frameworks and libraries for building modern, interactive user interfaces.',
    gradient: 'from-sky-500/20 to-blue-500/20',
    iconColor: 'text-sky-300',
    recommended: 'React',
  },
  {
    id: 'backend',
    name: 'Backend',
    icon: Server,
    providers: 7,
    description: 'Runtimes and frameworks for APIs, business logic, and server-side processing.',
    gradient: 'from-zinc-500/20 to-slate-500/20',
    iconColor: 'text-zinc-300',
    recommended: 'Node.js',
  },
  {
    id: 'authentication',
    name: 'Authentication',
    icon: ShieldCheck,
    providers: 7,
    description: 'OAuth, magic links, biometrics, and session management for secure user login.',
    gradient: 'from-amber-500/20 to-orange-500/20',
    iconColor: 'text-amber-300',
    recommended: 'Clerk',
  },
  {
    id: 'database',
    name: 'Database',
    icon: Database,
    providers: 8,
    description: 'SQL, NoSQL, vector, and real-time databases to store and query your data.',
    gradient: 'from-emerald-500/20 to-teal-500/20',
    iconColor: 'text-emerald-300',
    recommended: 'PostgreSQL',
  },
  {
    id: 'hosting',
    name: 'Hosting',
    icon: Cloud,
    providers: 7,
    description: 'Deploy and scale your frontend, backend, and serverless functions globally.',
    gradient: 'from-violet-500/20 to-blue-500/20',
    iconColor: 'text-violet-300',
    recommended: 'Vercel',
  },
  {
    id: 'cloud',
    name: 'Cloud',
    icon: CloudCog,
    providers: 6,
    description: 'Infrastructure providers for compute, networking, and managed services.',
    gradient: 'from-orange-500/20 to-amber-500/20',
    iconColor: 'text-orange-300',
    recommended: 'Amazon Web Services',
  },
  {
    id: 'storage',
    name: 'Storage',
    icon: HardDrive,
    providers: 7,
    description: 'File and object storage solutions for images, videos, and user uploads.',
    gradient: 'from-pink-500/20 to-rose-500/20',
    iconColor: 'text-pink-300',
    recommended: 'Cloudinary',
  },
  {
    id: 'payments',
    name: 'Payments',
    icon: CreditCard,
    providers: 7,
    description: 'Payment processing, subscriptions, and billing infrastructure.',
    gradient: 'from-emerald-500/20 to-green-500/20',
    iconColor: 'text-emerald-300',
    recommended: 'Stripe',
  },
  {
    id: 'email',
    name: 'Email',
    icon: Mail,
    providers: 7,
    description: 'Transactional and marketing email APIs with templates and deliverability.',
    gradient: 'from-indigo-500/20 to-blue-500/20',
    iconColor: 'text-indigo-300',
    recommended: 'Resend',
  },
  {
    id: 'analytics',
    name: 'Analytics',
    icon: BarChart3,
    providers: 7,
    description: 'Product analytics, event tracking, and user behavior insights.',
    gradient: 'from-cyan-500/20 to-sky-500/20',
    iconColor: 'text-cyan-300',
    recommended: 'PostHog',
  },
  {
    id: 'ai-models',
    name: 'AI Models',
    icon: Brain,
    providers: 7,
    description: 'Model inference and hosting platforms to run AI and machine learning workloads.',
    gradient: 'from-fuchsia-500/20 to-pink-500/20',
    iconColor: 'text-fuchsia-300',
    recommended: 'Hugging Face',
  },
  {
    id: 'llm',
    name: 'LLM',
    icon: Sparkles,
    providers: 7,
    description: 'Large language model APIs for chat, generation, and AI-powered features.',
    gradient: 'from-violet-500/20 to-purple-500/20',
    iconColor: 'text-violet-300',
    recommended: 'OpenAI',
  },
  {
    id: 'search',
    name: 'Search',
    icon: Search,
    providers: 8,
    description: 'Full-text, typo-tolerant, and vector search engines and APIs.',
    gradient: 'from-blue-500/20 to-indigo-500/20',
    iconColor: 'text-blue-300',
    recommended: 'Meilisearch',
  },
  {
    id: 'caching',
    name: 'Caching',
    icon: Zap,
    providers: 6,
    description: 'In-memory and edge caches to speed up reads and reduce latency.',
    gradient: 'from-yellow-500/20 to-amber-500/20',
    iconColor: 'text-yellow-300',
    recommended: 'Redis',
  },
  {
    id: 'monitoring',
    name: 'Monitoring',
    icon: Activity,
    providers: 6,
    description: 'Observability for metrics, traces, uptime, and application performance.',
    gradient: 'from-rose-500/20 to-red-500/20',
    iconColor: 'text-rose-300',
    recommended: 'Datadog',
  },
  {
    id: 'logging',
    name: 'Logging',
    icon: ScrollText,
    providers: 6,
    description: 'Centralized log aggregation, querying, and analysis.',
    gradient: 'from-slate-500/20 to-zinc-500/20',
    iconColor: 'text-slate-300',
    recommended: 'Better Stack',
  },
  {
    id: 'cms',
    name: 'CMS',
    icon: LayoutDashboard,
    providers: 7,
    description: 'Content management systems for structured content and editing workflows.',
    gradient: 'from-teal-500/20 to-emerald-500/20',
    iconColor: 'text-teal-300',
    recommended: 'Sanity',
  },
  {
    id: 'deployment',
    name: 'Deployment',
    icon: Rocket,
    providers: 7,
    description: 'Platforms for shipping, hosting, and releasing your applications.',
    gradient: 'from-orange-500/20 to-red-500/20',
    iconColor: 'text-orange-300',
    recommended: 'Vercel',
  },
  {
    id: 'maps',
    name: 'Maps',
    icon: Map,
    providers: 7,
    description: 'Mapping, geocoding, routing, and location-based services.',
    gradient: 'from-green-500/20 to-emerald-500/20',
    iconColor: 'text-green-300',
    recommended: 'Google Maps Platform',
  },
  {
    id: 'ocr',
    name: 'OCR',
    icon: ScanText,
    providers: 7,
    description: 'Optical character recognition to extract text from images and documents.',
    gradient: 'from-cyan-500/20 to-blue-500/20',
    iconColor: 'text-cyan-300',
    recommended: 'Tesseract OCR',
  },
  {
    id: 'translation',
    name: 'Translation',
    icon: Languages,
    providers: 6,
    description: 'Machine translation APIs and localization tooling.',
    gradient: 'from-indigo-500/20 to-violet-500/20',
    iconColor: 'text-indigo-300',
    recommended: 'Google Cloud Translation',
  },
  {
    id: 'voice',
    name: 'Voice',
    icon: Mic,
    providers: 7,
    description: 'Speech-to-text, text-to-speech, and voice call APIs.',
    gradient: 'from-purple-500/20 to-fuchsia-500/20',
    iconColor: 'text-purple-300',
    recommended: 'ElevenLabs',
  },
  {
    id: 'chat',
    name: 'Chat',
    icon: MessageSquare,
    providers: 6,
    description: 'In-app chat, messaging, and realtime communication APIs.',
    gradient: 'from-blue-500/20 to-sky-500/20',
    iconColor: 'text-blue-300',
    recommended: 'Sendbird',
  },
  {
    id: 'notifications',
    name: 'Notifications',
    icon: Bell,
    providers: 7,
    description: 'Push notifications, in-app messaging, and multi-channel alert systems.',
    gradient: 'from-fuchsia-500/20 to-pink-500/20',
    iconColor: 'text-fuchsia-300',
    recommended: 'OneSignal',
  },
  {
    id: 'testing',
    name: 'Testing',
    icon: FlaskConical,
    providers: 7,
    description: 'Unit, integration, and end-to-end testing frameworks and tools.',
    gradient: 'from-amber-500/20 to-yellow-500/20',
    iconColor: 'text-amber-300',
    recommended: 'Jest',
  },
  {
    id: 'devops',
    name: 'DevOps',
    icon: Workflow,
    providers: 6,
    description: 'Infrastructure as code and configuration management tooling.',
    gradient: 'from-slate-500/20 to-gray-500/20',
    iconColor: 'text-slate-300',
    recommended: 'Terraform',
  },
  {
    id: 'containerization',
    name: 'Containerization',
    icon: Box,
    providers: 7,
    description: 'Containers, orchestration, and related runtimes for packaging apps.',
    gradient: 'from-blue-500/20 to-cyan-500/20',
    iconColor: 'text-blue-300',
    recommended: 'Docker',
  },
  {
    id: 'serverless',
    name: 'Serverless',
    icon: CloudLightning,
    providers: 7,
    description: 'Function-as-a-service platforms that scale to zero and back.',
    gradient: 'from-violet-500/20 to-indigo-500/20',
    iconColor: 'text-violet-300',
    recommended: 'AWS Lambda',
  },
  {
    id: 'ci-cd',
    name: 'CI/CD',
    icon: Repeat,
    providers: 7,
    description: 'Continuous integration and continuous delivery pipelines.',
    gradient: 'from-emerald-500/20 to-teal-500/20',
    iconColor: 'text-emerald-300',
    recommended: 'GitHub Actions',
  },
  {
    id: 'video-apis',
    name: 'Video APIs',
    icon: Video,
    providers: 7,
    description: 'Video streaming, transcoding, live streaming, and player SDKs.',
    gradient: 'from-violet-500/20 to-purple-500/20',
    iconColor: 'text-violet-300',
    recommended: 'Mux',
  },
  {
    id: 'cdn',
    name: 'CDN',
    icon: Globe,
    providers: 7,
    description: 'Global content delivery networks for low-latency asset distribution.',
    gradient: 'from-blue-500/20 to-cyan-500/20',
    iconColor: 'text-blue-300',
    recommended: 'Cloudflare',
  },
];

export const fallbackCategory: Category = {
  id: 'technology',
  name: 'Technology',
  icon: Layers,
  providers: 0,
  description: '',
  gradient: 'from-slate-500/20 to-zinc-500/20',
  iconColor: 'text-slate-300',
  recommended: '',
};

export function getCategoryMeta(id: string): Category {
  return categories.find((c) => c.id === id) ?? fallbackCategory;
}
