export type FaqItem = {
  question: string;
  answer: string;
  category: string;
  featured?: boolean;
};

export const faqCategories = ['General', 'Pricing', 'AI & Models', 'Providers', 'Stack & Export'];

export const faqItems: FaqItem[] = [
  {
    question: 'What is Stack2Set?',
    answer:
      'Stack2Set is an AI-powered developer tool that analyzes a project idea and recommends the best technologies, APIs, databases, authentication providers, hosting services, and developer tools to build it without searching randomly.',
    category: 'General',
    featured: true,
  },
  {
    question: 'How does Stack2Set work?',
    answer:
      "Describe your project in plain English. Stack2Set's AI analyzes your idea, identifies the required technology categories, and returns the best and filter-based providers, listed on the UI with provider details, links, and explanations for each one.",
    category: 'General',
  },
  {
    question: 'Does Stack2Set support startups?',
    answer:
      'Yes. Stack2Set is designed for developers of all levels, from solo builders to startups. It recommends production-ready, cost-effective, and free-tier options so early-stage teams can move fast without expensive research.',
    category: 'General',
    featured: true,
  },
  {
    question: 'Why should I use Stack2Set instead of searching manually?',
    answer:
      'Stack2Set saves hours of research by analyzing your whole project at once, covering every technology category, ranking providers, and explaining why each one fits — all in one place.',
    category: 'General',
  },
  {
    question: 'Is Stack2Set free?',
    answer:
      'Yes, Stack2Set is free to use. You can describe unlimited project ideas and explore recommended providers without any cost.',
    category: 'Pricing',
    featured: true,
  },
  {
    question: 'Which AI models are supported?',
    answer:
      'Stack2Set is powered by modern large language models. It uses the Google Gemini API for analysis and can also leverage AI models for recommendations. Providers for AI models, LLMs, and vector databases are recommended as part of your stack when your project needs them.',
    category: 'AI & Models',
    featured: true,
  },
  {
    question: 'How are technologies recommended?',
    answer:
      'Recommendations are generated by AI using criteria such as popularity, reliability, production readiness, active maintenance, community adoption, documentation quality, free tier availability, ease of integration, security, scalability, and performance. Each provider is ranked and explained.',
    category: 'AI & Models',
    featured: true,
  },
  {
    question: 'How accurate are recommendations?',
    answer:
      'Recommendations are produced by AI models using up-to-date knowledge and structured ranking criteria. Always verify the final choice against your specific requirements and budget.',
    category: 'AI & Models',
  },
  {
    question: 'Does Stack2Set use AI?',
    answer:
      'Yes. Stack2Set uses AI models to analyze your project description and generate technology recommendations automatically.',
    category: 'AI & Models',
  },
  {
    question: 'How often are recommendations updated?',
    answer:
      'Recommendation quality is continuously improved as the underlying AI models and provider data are updated. Because analysis runs on your latest project description, results are always generated fresh.',
    category: 'AI & Models',
  },
  {
    question: 'Can I compare providers?',
    answer:
      'Yes. Every category page lists multiple providers with descriptions, tags, free-tier and open-source indicators, so you can compare options before adding one to your stack.',
    category: 'Providers',
    featured: true,
  },
  {
    question: 'Will more providers be added?',
    answer:
      'Yes. The provider library is constantly growing. New authentication, database, cloud, AI, and tooling providers are added as they become reliable, production-ready options.',
    category: 'Providers',
    featured: true,
  },
  {
    question: 'Can Stack2Set recommend AI tools?',
    answer:
      'Yes. Stack2Set can recommend AI models, LLM providers, and AI-powered tools when your project requires them, including vector databases and machine learning APIs.',
    category: 'Providers',
  },
  {
    question: 'Can Stack2Set recommend databases?',
    answer:
      "Yes. Stack2Set recommends SQL, NoSQL, vector, and real-time databases and explains which type best fits your project's data needs.",
    category: 'Providers',
  },
  {
    question: 'Which frontend frameworks are supported?',
    answer:
      'Stack2Set can recommend frontend frameworks such as React, Next.js, Vue, Svelte, and more based on the specific needs of your project.',
    category: 'Providers',
  },
  {
    question: 'Which backend frameworks are supported?',
    answer:
      'Stack2Set can recommend backend frameworks including Node.js/Express, NestJS, Python/Django, FastAPI, Ruby on Rails, Go, and others depending on your project requirements.',
    category: 'Providers',
  },
  {
    question: 'Which databases are supported?',
    answer:
      'Stack2Set covers major databases such as PostgreSQL, MySQL, MongoDB, Redis, and serverless and vector databases, recommending the best fit for your data model and scale.',
    category: 'Providers',
  },
  {
    question: 'Does Stack2Set recommend cloud providers?',
    answer:
      'Yes. Stack2Set recommends cloud platforms and hosting providers such as AWS, Vercel, Netlify, Railway, and others, matched to your deployment needs.',
    category: 'Providers',
  },
  {
    question: 'Can I discover APIs?',
    answer:
      'Yes. Stack2Set helps you discover APIs for payments, email, search, maps, AI, authentication, storage, and hundreds of other use cases.',
    category: 'Providers',
  },
  {
    question: 'Does Stack2Set recommend open-source tools?',
    answer:
      'Yes. Providers are marked with open-source indicators, and Stack2Set frequently recommends open-source tools when they are the best fit for a project.',
    category: 'Providers',
  },
  {
    question: 'Can I export my stack?',
    answer:
      'Yes. Once you assemble your stack, you can review your current stack and export it as a shareable summary of all the providers and categories you selected.',
    category: 'Stack & Export',
    featured: true,
  },
  {
    question: 'Can beginners use Stack2Set?',
    answer:
      'Absolutely. Stack2Set is designed for developers of all levels. Beginners can discover a sensible stack without deep research, and each recommendation includes an explanation.',
    category: 'Stack & Export',
  },
];

export const featuredFaqItems = faqItems.filter((item) => item.featured);
