export type AnalysisProvider = {
  id: string;
  rank?: number;
  name: string;
  description: string;
  reason?: string;
  bestUseCases?: string[];
  website?: string;
  documentation?: string;
  freeTier?: boolean;
  pricingModel?: string;
  popularityScore?: number;
  openSource?: boolean;
  tags?: string[];
  /** Set when the provider was generated by the AI because the database had no matches. */
  aiSuggested?: boolean;
};

export type AnalysisCategory = {
  id: string;
  name: string;
  description: string;
  confidence?: number;
  reasoning?: string;
  providers: AnalysisProvider[];
};

export type Complexity = 'Low' | 'Medium' | 'High';

export type StackAnalysis = {
  projectType: string;
  summary: string;
  complexity: Complexity;
  categories: AnalysisCategory[];
  integrations?: AnalysisCategory[];
};
