import type { Metadata } from 'next';
import { Footer } from '@/components/landing/footer';
import { Navbar } from '@/components/landing/navbar';
import { siteConfig } from '@/lib/site';
import { faqSchema } from '@/lib/jsonld';

export const metadata: Metadata = {
  title: 'FAQ',
  description:
    'Answers to common questions about StackPilot: how it works, whether it is free, how technologies are recommended, supported frameworks and databases, and more.',
  alternates: {
    canonical: '/faq',
  },
  openGraph: {
    type: 'website',
    title: `FAQ — ${siteConfig.name}`,
    description:
      'Answers to common questions about StackPilot: how it works, whether it is free, and how technologies are recommended.',
  },
};

const faqQuestions = [
  {
    question: 'What is StackPilot?',
    answer:
      'StackPilot is an AI-powered developer tool that analyzes a project idea and recommends the best technologies, APIs, databases, authentication providers, hosting services, and developer tools to build it without searching randomly.',
  },
  {
    question: 'How does StackPilot work?',
    answer:
      'Describe your project in plain English. StackPilot\'s AI analyzes your idea, identifies the required technology categories, and returns to database and from that the best and filter based providers are listed on UI and with providers details and links with explanations for each one.',
  },
  {
    question: 'Is StackPilot free?',
    answer:
      'Yes, StackPilot is free to use. You can describe unlimited project ideas and explore recommended providers without any cost.',
  },
  {
    question: 'How are technologies recommended?',
    answer:
      'Recommendations are generated by AI using criteria such as popularity, reliability, production readiness, active maintenance, community adoption, documentation quality, free tier availability, ease of integration, security, scalability, and performance.',
  },
  {
    question: 'Can StackPilot recommend AI tools?',
    answer:
      'Yes. StackPilot can recommend AI models, LLM providers, and AI-powered tools when your project requires them, including vector databases and machine learning APIs.',
  },
  {
    question: 'Can StackPilot recommend databases?',
    answer:
      'Yes. StackPilot recommends SQL, NoSQL, vector, and real-time databases and explains which type best fits your project\'s data needs.',
  },
  {
    question: 'Can I compare providers?',
    answer:
      'Yes. Every category page lists multiple providers with descriptions, tags, free-tier and open-source indicators, so you can compare options before adding one to your stack.',
  },
  {
    question: 'How accurate are recommendations?',
    answer:
      'Recommendations are produced by AI models using up-to-date knowledge and structured ranking criteria. Always verify the final choice against your specific requirements and budget.',
  },
  {
    question: 'Does StackPilot recommend open-source tools?',
    answer:
      'Yes. Providers are marked with open-source indicators, and StackPilot frequently recommends open-source tools when they are the best fit for a project.',
  },
  {
    question: 'Which frontend frameworks are supported?',
    answer:
      'StackPilot can recommend frontend frameworks such as React, Next.js, Vue, Svelte, and more based on the specific needs of your project.',
  },
  {
    question: 'Which backend frameworks are supported?',
    answer:
      'StackPilot can recommend backend frameworks including Node.js/Express, NestJS, Python/Django, FastAPI, Ruby on Rails, Go, and others depending on your project requirements.',
  },
  {
    question: 'Which databases are supported?',
    answer:
      'StackPilot covers major databases such as PostgreSQL, MySQL, MongoDB, Redis, and serverless and vector databases, recommending the best fit for your data model and scale.',
  },
  {
    question: 'Does StackPilot recommend cloud providers?',
    answer:
      'Yes. StackPilot recommends cloud platforms and hosting providers such as AWS, Vercel, Netlify, Railway, and others, matched to your deployment needs.',
  },
  {
    question: 'Can I discover APIs?',
    answer:
      'Yes. StackPilot helps you discover APIs for payments, email, search, maps, AI, authentication, storage, and hundreds of other use cases.',
  },
  {
    question: 'Does StackPilot use AI?',
    answer:
      'Yes. StackPilot uses AI models to analyze your project description and generate technology recommendations automatically.',
  },
  {
    question: 'Can beginners use StackPilot?',
    answer:
      'Absolutely. StackPilot is designed for developers of all levels. Beginners can discover a sensible stack without deep research, and each recommendation includes an explanation.',
  },
  {
    question: 'How often are recommendations updated?',
    answer:
      'Recommendation quality is continuously improved as the underlying AI models and provider data are updated. Because analysis runs on your latest project description, results are always generated fresh.',
  },
  {
    question: 'Why should I use StackPilot instead of searching manually?',
    answer:
      'StackPilot saves hours of research by analyzing your whole project at once, covering every technology category, ranking providers, and explaining why each one fits — all in one place.',
  },
];

export default function FAQPage() {
  const jsonLd = faqSchema(faqQuestions);

  return (
    <main className="relative min-h-screen overflow-x-hidden">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <Navbar />

      <div className="relative overflow-hidden px-6 pb-20 pt-32">
        <div className="pointer-events-none absolute left-1/2 top-0 -z-10 h-[400px] w-[700px] -translate-x-1/2 rounded-full bg-violet-600/10 blur-[120px]" />

        <section className="mx-auto max-w-3xl">
          <header className="text-center">
            <p className="text-sm font-medium text-violet-400">FAQ</p>
            <h1 className="mt-3 text-4xl font-semibold tracking-tight text-foreground sm:text-5xl">
              Frequently Asked <span className="gradient-text">Questions</span>
            </h1>
            <p className="mx-auto mt-4 max-w-xl text-lg text-muted-foreground">
              Everything you need to know about StackPilot and how it recommends the best technology stack for your project.
            </p>
          </header>

          <section className="mt-12 space-y-4">
            {faqQuestions.map((item) => (
              <details
                key={item.question}
                className="glass glass-hover group rounded-2xl p-6"
              >
                <summary className="cursor-pointer list-none text-base font-semibold text-foreground">
                  {item.question}
                </summary>
                <p className="mt-3 text-sm leading-relaxed text-muted-foreground">{item.answer}</p>
              </details>
            ))}
          </section>
        </section>
      </div>

      <Footer />
    </main>
  );
}
